Repository CESNET/perun, pull requests merged in 2018-07, with the labels that each got.

#1899 set scope of Oracle dependencies in perun-core to test
  perun-core/pom.xml
Labels: merge soon

#1900 CORE: Allow RPC role to read attributes
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
Labels: waiting for review

#1898 replaced hardcoded perun version with version read from pom.xml
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/PerunBl.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/Api.java
Labels: merge soon

#1912 Deleted ExecService and all its occurrences.
  perun-base/src/main/java/cz/metacentrum/perun/taskslib/model/ExecService.java
  perun-cli/Perun/Common.pm
  perun-cli/Perun/GeneralServiceAgent.pm
  perun-cli/Perun/beans/ExecService.pm
  perun-dispatcher/src/test/java/cz/metacentrum/perun/dispatcher/unit/EventProcessorTest.java
  perun-dispatcher/src/test/java/cz/metacentrum/perun/dispatcher/unit/EventServiceResolverTest.java
  perun-dispatcher/src/test/java/cz/metacentrum/perun/dispatcher/unit/SchedulingPoolTest.java
  perun-engine/src/test/java/cz/metacentrum/perun/engine/AbstractEngineTest.java
  perun-rpc-lib/src/main/java/cz/metacentrum/perun/rpclib/Rpc.java
  perun-tasks-lib/src/main/java/cz/metacentrum/perun/controller/service/PropagationStatsReader.java
  perun-tasks-lib/src/main/java/cz/metacentrum/perun/controller/service/impl/GeneralServiceManagerImpl.java
  perun-tasks-lib/src/main/java/cz/metacentrum/perun/controller/service/impl/PropagationStatsReaderImpl.java
  perun-tasks-lib/src/main/java/cz/metacentrum/perun/taskslib/dao/TaskDao.java
  perun-tasks-lib/src/main/java/cz/metacentrum/perun/taskslib/dao/jdbc/ServiceDenialDaoJdbc.java
  perun-tasks-lib/src/main/java/cz/metacentrum/perun/taskslib/service/impl/TaskStoreImpl.java
  perun-tasks-lib/src/main/resources/perun-tasks-lib.xml
  perun-tasks-lib/src/test/java/cz/metacentrum/perun/taskslib/dao/ServiceDenialDaoTest.java
Labels: merge soon, waiting for changes
