Repository CESNET/perun, pull requests merged in 2018-02, with the labels that each got.

#1761 Implementation of reCAPTCHA V2
  perun-core/pom.xml
  perun-rpc/pom.xml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/RegistrarManagerMethod.java
  pom.xml
Labels: waiting for changes

#1749 Edited synchronization and group arithmetic.
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/GroupOperationsException.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/GroupsManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/MembersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/UsersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/GroupsManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/UsersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/UsersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/GroupsManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/UsersManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/GroupsManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/api/AuthzResolverIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/SecurityTeamsManagerEntryIntegrationTest.java
  perun-voot/src/test/java/cz/metacentrum/perun/voot/VOOTLimitResultIntegrationTest.java
  perun-voot/src/test/java/cz/metacentrum/perun/voot/VOOTMainAndFilterIntegrationTest.java
  perun-voot/src/test/java/cz/metacentrum/perun/voot/VOOTSortIntegrationTest.java
  perun-voot/src/test/java/cz/metacentrum/perun/voot/VOOTSubGroupsIntegrationTest.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/JsonErrorHandler.java
Labels: merge soon

#1757 unique attributes
  perun-auditparser/src/main/java/cz/metacentrum/perun/auditparser/AuditParser.java
  perun-auditparser/src/test/java/cz/metacentrum/perun/auditparser/AuditParserTest.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/Attribute.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/AttributeDefinition.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/BeansUtils.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/AttributeAlreadyMarkedUniqueException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/WrongAttributeValueException.java
  perun-base/src/test/resources/logback-test.xml
  perun-base/src/test/resources/test-data.sql
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/java/cz/metacentrum/perun/core/api/AttributesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/AttributesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/AttributesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AttributesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Compatibility.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_resource_attribute_def_def_o365EmailAddresses_mu.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_attribute_def_def_o365EmailAddresses_mu.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/AttributesManagerImplApi.java
  perun-core/src/main/resources/hsqldbChangelog.txt
  perun-core/src/main/resources/oracleChangelog.txt
  perun-core/src/main/resources/postgresChangelog.txt
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/AttributesManagerEntryIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_resource_attribute_def_def_isUnixGroupIntegrationtest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_resource_attribute_def_def_o365EmailAddresses_muTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_attribute_def_def_o365EmailAddresses_muTest.java
  perun-db/oracle.sql
  perun-db/postgres.sql
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/AttributesManagerMethod.java
Labels: waiting for review

#1756 New attributes to LDAPc
  perun-ldapc-initializer/src/main/java/cz/metacentrum/perun/ldapc/initializer/utils/Utils.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/processor/LdapConnector.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/processor/impl/EventProcessorImpl.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/processor/impl/LdapConnectorImpl.java
Labels: merge soon
