Repository CESNET/perun, pull requests merged in 2019-11, with the labels that each got.

#2413 Separation of checkAttributeSyntax from semantics in Facility modules
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_accountExpirationTime.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_googleGroupsDomain.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_homeDirUmask.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_homeMountPoint_passwd_scp.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_homeMountPoints.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_ldapBaseDN.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_login_namespace.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_passwdScpDestinationFile.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_pbsServer.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_quotaEnabled.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_reqAups.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_rtOutputFileName.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_scratchDirPermissions.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_scratchLocalDirPermissions.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_shell_passwd_scp.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_shells.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_uid_namespace.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_unixGID_namespace.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_unixGroupName_namespace.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_virt_GIDRanges.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_virt_maxUID.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_virt_minUID.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_accountExpirationTimeTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_googleGroupsDomainTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_homeDirUmaskTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_homeMountPoint_passwd_scpTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_homeMountPointsTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_ldapBaseDNTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_login_namespaceTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_passwdScpDestinationFileTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_pbsServerTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_quotaEnabledTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_reqAupsTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_rtOutputFileNameTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_scratchDirPermissionsTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_scratchLocalDirPermissionsTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_shell_passwd_scpTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_shellsTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_uid_namespaceTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_unixGID_namespaceTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_unixGroupName_namespaceTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_virt_GIDRangesTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_virt_maxUIDTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_virt_minUIDTest.java
Labels: merge soon

#2460 Allow also partial matching for String attribute in Searcher
  perun-core/src/main/java/cz/metacentrum/perun/core/api/Searcher.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/SearcherBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/SearcherBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/SearcherEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/SearcherImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/SearcherImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/SearcherEntryIntegrationTest.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/SearcherMethod.java
Labels: merge soon

#2456 Creating AuditEvents about removing admins of a deleted entity
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/FacilitiesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ResourcesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/SecurityTeamsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/VosManagerBlImpl.java
Labels: merge soon

#2441 Moving functionality from GeneralServiceManager to ServicesManager
  perun-cli/Perun/Agent.pm
  perun-cli/Perun/GeneralServiceAgent.pm
  perun-cli/Perun/ServicesAgent.pm
  perun-cli/forceServicePropagation
  perun-core/src/main/java/cz/metacentrum/perun/controller/service/GeneralServiceManager.java
  perun-core/src/main/java/cz/metacentrum/perun/controller/service/impl/GeneralServiceManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/controller/service/impl/PropagationStatsReaderImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/ServicesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ServicesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ServicesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ServicesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ServicesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/ServicesManagerImplApi.java
  perun-core/src/main/java/cz/metacentrum/perun/taskslib/dao/ServiceDenialDao.java
  perun-core/src/main/java/cz/metacentrum/perun/taskslib/dao/jdbc/ServiceDenialDaoJdbc.java
  perun-core/src/main/resources/perun-core.xml
  perun-core/src/test/java/cz/metacentrum/perun/core/bl/ServicesManagerBlImplTest.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/processing/EventProcessor.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/processing/impl/EventServiceResolverImpl.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/scheduling/TaskScheduler.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/scheduling/impl/SchedulingPoolImpl.java
  perun-dispatcher/src/test/java/cz/metacentrum/perun/dispatcher/AbstractDispatcherTest.java
  perun-engine/src/test/java/cz/metacentrum/perun/engine/AbstractEngineTest.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/ApiCaller.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/GeneralServiceManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ServicesManagerMethod.java
Labels: merge soon

#2461 createSponsoredMember will accept separated name with titles in a map
  perun-core/src/main/java/cz/metacentrum/perun/core/api/MembersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/MembersManagerEntryIntegrationTest.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/MembersManagerMethod.java
Labels: merge soon

#2475 RPC: Remove requirement on POST for check/get methods
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/MembersManagerMethod.java
Labels: merge soon

#2485 ENGINE, DISPATCHER: Make constant for stuck tasks configurable
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/scheduling/PropagationMaintainer.java
  perun-dispatcher/src/main/resources/perun-dispatcher.xml
  perun-engine/src/main/java/cz/metacentrum/perun/engine/scheduling/impl/GenWorkerImpl.java
  perun-engine/src/main/java/cz/metacentrum/perun/engine/scheduling/impl/PropagationMaintainerImpl.java
  perun-engine/src/main/resources/perun-engine.xml
Labels: important, merge soon

#2477 Fix problem with removing member from group while synchronization
  perun-base/src/main/java/cz/metacentrum/perun/core/api/BeansUtils.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ExtSourcesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
Labels: manual test needed, merge soon

#2464 Implementation of authorization
  perun-base/src/main/java/cz/metacentrum/perun/core/api/PerunPolicy.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/AuthzResolver.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AuthzResolverImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunPoliciesContainer.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunRolesLoader.java
  perun-core/src/test/java/cz/metacentrum/perun/core/api/AuthzResolverIntegrationTest.java
Labels: merge soon

#2487 Fix authorization in VosManagerEntry
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/VosManagerEntry.java
Labels: merge soon, waiting for review

#2491 Remove slash on the end of normalized path
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ModulesUtilsBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ModulesUtilsBlImpl.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/ModulesUtilsEntryIntegrationTest.java
Labels: merge soon

#2489 Another fix of VosManagerEntry authorization
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/VosManagerEntry.java
Labels: merge soon, waiting for changes

#2476 CORE, REGISTRAR: Added authz to canBeMember*() methods
  perun-core/src/main/java/cz/metacentrum/perun/core/api/MembersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/ConsolidatorManagerImpl.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/MailManagerImpl.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/BBMRICollections.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/BBMRINetworks.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/EduTEAMS.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/Eduroam.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/ElixirBonaFideStatus.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/Metacentrum.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/Sitola.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/Vsup.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/JsonErrorHandler.java
Labels: merge soon

#2503 implemented Perun RPC client in Python
  perun-cli-java/pom.xml
  perun-cli-java/src/main/java/cz/metacentrum/perun/cli/PerunCLI.java
  perun-cli-java/src/main/java/cz/metacentrum/perun/cli/PerunCommand.java
  perun-cli-java/src/main/java/cz/metacentrum/perun/cli/commands/AddFacilityOwner.java
  perun-cli-java/src/main/java/cz/metacentrum/perun/cli/commands/GetDestinationOwners.java
  perun-cli-java/src/main/java/cz/metacentrum/perun/cli/commands/GetRichUser.java
  perun-cli-java/src/main/java/cz/metacentrum/perun/cli/commands/ListOfAllowedVosOnFacility.java
  perun-cli-java/src/main/java/cz/metacentrum/perun/cli/commands/ListOfFacilityGroups.java
  perun-cli-java/src/main/java/cz/metacentrum/perun/cli/commands/ListOfFacilityOwners.java
  perun-cli-java/src/main/java/cz/metacentrum/perun/cli/commands/ListOfVos.java
  perun-cli-java/src/main/java/cz/metacentrum/perun/cli/commands/PerunStatus.java
  perun-cli-java/src/main/java/cz/metacentrum/perun/cli/commands/RemoveFacilityOwner.java
  perun-cli-java/src/main/java/cz/metacentrum/perun/cli/commands/SetFacilityHostsAttributeValue.java
  perun-cli-java/src/main/resources/logback.xml
  perun-cli-python/README.md
  perun-cli-python/generate.sh
  perun-cli-python/get_user.py
  pom.xml
Labels: merge soon
