Repository CESNET/perun, pull requests merged in 2019-06, with the labels that each got.

#2179 Added new wrappers to getData methods
  perun-core/src/main/java/cz/metacentrum/perun/core/api/ServicesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/FacilitiesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ResourcesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ServicesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/FacilitiesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ResourcesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ServicesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ServicesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ResourcesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/ResourcesManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/ServicesManagerEntryIntegrationTest.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ServicesManagerMethod.java
Labels: merge soon, waiting for changes

#2241 Modified user:virt:eduPersonEntitlement
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_eduPersonEntitlement.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_eduPersonEntitlementTest.java
Labels: merge soon

#2213 Group structure synchronization split
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_groupStructureSynchronizationEnabled.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_synchronizationEnabled.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupStructureSynchronizationIntegrationTest.java
Labels: merge soon, waiting for review

#2246 Expiration of member need to check validity of attributes
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/resources/perun-core.xml
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/ExpirationNotifScheduler.java
Labels: external opinion needed, merge soon

#2262 Added new attribute lastAccess to UserExtSource
  perun-auditparser/src/main/java/cz/metacentrum/perun/auditparser/AuditParser.java
  perun-auditparser/src/test/java/cz/metacentrum/perun/auditparser/AuditParserTest.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/UserExtSource.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/UsersManagerImpl.java
Labels: merge soon

#2249 Member locks
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
Labels: merge soon

#2233 Scheduling for synchronizations
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/SynchronizationPool.java
Labels: waiting for review
