Repository CESNET/perun, pull requests merged in 2019-10, with the labels that each got.

#2408 Various changes in SCIM module
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/Api.java
  perun-scim/src/main/java/cz/metacentrum/perun/scim/api/endpoints/ResourceTypesEndpointController.java
  perun-scim/src/main/java/cz/metacentrum/perun/scim/api/endpoints/UserResourceEndpointController.java
  perun-scim/src/main/java/cz/metacentrum/perun/scim/api/entities/GroupSCIM.java
  perun-scim/src/main/java/cz/metacentrum/perun/scim/api/entities/UserSCIM.java
  perun-scim/src/test/java/cz/metacentrum/perun/scim/AbstractSCIMTest.java
Labels: merge soon

#2420 Audit log for sending invitations to VO/group
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/MailManagerEvents/InvitationSentEvent.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/MailManagerImpl.java
Labels: merge soon

#2424 added rpc method: deleteAttributes
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/AttributesManagerMethod.java
Labels: waiting for changes

#2401 Javadoc for exceptions
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ActionTypeNotExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/AlreadyMemberException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/AlreadyReservedLoginException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/AlreadySponsorException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/AlreadySponsoredMemberException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/AttributeAlreadyAssignedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/AttributeAlreadyMarkedUniqueException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/AttributeDefinitionExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/AttributeNotAssignedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/AttributeNotExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/AttributeValueException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/BanAlreadyExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/BanNotExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/CandidateNotExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ClusterNotExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ConsistencyErrorException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/DestinationAlreadyAssignedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/DestinationAlreadyRemovedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/DestinationExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/DestinationNotExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/DiacriticNotAllowedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/EntityAlreadyAssignedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/EntityExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/EntityNotAssignedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/EntityNotExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ExtSourceAlreadyAssignedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ExtSourceAlreadyRemovedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ExtSourceExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ExtSourceInUseException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ExtSourceNotAssignedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ExtSourceNotExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ExtSourceUnsupportedOperationException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ExternallyManagedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/FacilityAlreadyRemovedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/FacilityContactExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/FacilityContactNotExistsException.java
Labels: waiting for review

#2430 Javadoc for exceptions
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/FacilityExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/FacilityNotExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/GroupAlreadyAssignedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/GroupAlreadyRemovedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/GroupAlreadyRemovedFromResourceException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/GroupExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/GroupMoveNotAllowedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/GroupNotAdminException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/GroupNotDefinedOnResourceException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/GroupNotExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/GroupRelationAlreadyExists.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/GroupRelationCannotBeRemoved.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/GroupRelationDoesNotExist.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/GroupRelationNotAllowed.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/GroupResourceMismatchException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/GroupStructureSynchronizationAlreadyRunningException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/GroupSynchronizationAlreadyRunningException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/HostAlreadyRemovedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/HostExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/HostNotExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/IllegalArgumentException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/InvalidCertificateException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/LoginExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/LoginNotExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/MaxSizeExceededException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/MemberAlreadyRemovedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/MemberGroupMismatchException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/MemberNotExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/MemberNotSponsoredException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/MemberNotSuspendedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/MemberNotValidYetException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/MemberResourceMismatchException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/MembershipMismatchException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/MessageParsingFailException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/MinSizeExceededException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ModuleNotExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/NotGroupMemberException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/NotSpecificUserExpectedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/NumberNotInRangeException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/NumbersNotAllowedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/OwnerAlreadyAssignedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/OwnerAlreadyRemovedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/OwnerNotExistsException.java
Labels: merge soon

#2429 Javadoc for exceptions
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ParentGroupNotExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ParserException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/PasswordChangeFailedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/PasswordCreationFailedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/PasswordDeletionFailedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/PasswordDoesntMatchException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/PasswordOperationTimeoutException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/PasswordStrengthFailedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/PerunBeanNotSupportedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/PerunException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/QuotaNotInAllowedLimitException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/RelationExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/RelationNotExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ResourceAlreadyRemovedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ResourceExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ResourceNotExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ResourceTagAlreadyAssignedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ResourceTagNotAssignedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ResourceTagNotExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/RoleNotSupportedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/SecurityTeamAlreadyAssignedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/SecurityTeamExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/SecurityTeamNotAssignedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/SecurityTeamNotExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ServiceAlreadyAssignedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ServiceAlreadyBannedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ServiceAlreadyRemovedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ServiceAlreadyRemovedFromServicePackageException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ServiceExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ServiceNotAssignedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ServiceNotExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ServicesPackageExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ServicesPackageNotExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/SpaceNotAllowedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/SpecialCharsNotAllowedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/SpecificUserAlreadyRemovedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/SpecificUserExpectedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/SpecificUserMustHaveOwnerException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/SpecificUserOwnerAlreadyRemovedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/SubGroupCannotBeRemovedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/UserAlreadyBlacklistedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/UserExtSourceAlreadyRemovedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/UserExtSourceExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/UserExtSourceNotExistsException.java
Labels: merge soon, waiting for review

#2433 LDAPC: Allow switching ldap attributes to deleted state
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/model/PerunAttribute.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/model/impl/AbstractPerunEntry.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/model/impl/PerunAttributeDesc.java
  perun-ldapc/src/main/resources/perun-ldapc.xml
Labels: merge soon

#2419 new facility attributes
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/beans/ResourceSynchronizer.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/processor/impl/FacilityAttributeProcessor.java
  perun-ldapc/src/main/resources/perun-ldapc.xml
  perun-utils/ldapc-scripts/schemas/perun-schema.ldif
Labels: merge soon

#2417 Addition of RichUserExtSource
  perun-base/src/main/java/cz/metacentrum/perun/core/api/RichUserExtSource.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/AuthzResolver.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/UsersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/UsersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/UsersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/UsersManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/TestUtils.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/UsersManagerEntryIntegrationTest.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/UsersManagerMethod.java
Labels: merge soon

#2446 Changing adding of admins to the entities
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/FacilitiesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/GroupsManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ResourcesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/SecurityTeamsManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/VosManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/FacilitiesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ResourcesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/SecurityTeamsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/VosManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/GroupsManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/SecurityTeamsManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/VosManagerEntry.java
  perun-voot/src/test/java/cz/metacentrum/perun/voot/VOOTMainAndFilterIntegrationTest.java
  perun-voot/src/test/java/cz/metacentrum/perun/voot/VOOTSortIntegrationTest.java
Labels: merge soon

#2438 Initialization of roles from configuration file
  perun-base/src/test/resources/perun-roles.yml
  perun-core/pom.xml
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AuthzResolverImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunRolesLoader.java
  perun-core/src/main/resources/perun-core.xml
Labels: merge soon

#2458 Load and get perun policies
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/PolicyNotExistsException.java
  perun-base/src/test/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AuthzResolverImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunPoliciesContainer.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunRolesLoader.java
Labels: merge soon

#2453 New module for R:D:capabilities
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_resource_attribute_def_def_capabilities.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_resource_attribute_def_def_capabilitiesTest.java
Labels: merge soon, waiting for review

#2450 Separation of checkAttributeSyntax from semantics in User-Facility mo…
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_def_accountExpirationTime.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_def_basicDefaultGID.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_def_defaultUnixGID.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_def_homeMountPoint.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_def_o365AccountExtension.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_def_shell.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_def_shell_passwd_scp.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_virt_UID.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_virt_defaultUnixGID.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_virt_groupStatus.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_virt_login.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_virt_preferredUnixGroupName.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_def_accountExpirationTimeTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_def_basicDefaultGIDTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_def_defaultUnixGIDTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_def_homeMountPointTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_def_o365AccountExtensionTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_def_shellTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_def_shell_passwd_scpTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_virt_UIDTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_virt_defaultUnixGIDTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_virt_groupStatusTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_virt_loginTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_virt_preferredUnixGroupNameTest.java
Labels: merge soon
