Repository CESNET/perun, pull requests merged in 2019-08, with the labels that each got.

#2339 Fix of generating inverse strong dependencies
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
Labels: waiting for review

#2336 Utils: Added timeout for kerberos password manager
  perun-utils/password-manager/perun.passwordManager
Labels: waiting for review

#2338 Added checkAttributeSyntax to all layers of AttributesManager
  perun-core/src/main/java/cz/metacentrum/perun/core/api/AttributesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/AttributesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/AttributesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AttributesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/AttributesManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/AttributesManagerEntryIntegrationTestAbstract.java
Labels: merge soon

#2297 New module to collect additionalIdentifiers for User
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_additionalIdentifiers.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/modules/attributes/UserVirtualAttributeCollectedFromUserExtSource.java
Labels: manual test needed, waiting for review

#2342 Attribute dependencies tests
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
  perun-core/src/test/java/cz/metacentrum/perun/core/bl/AttributesManagerBlImplUnitTests.java
Labels: merge soon

#2301 Adding methods to remove member(s) from group(s)
  perun-core/src/main/java/cz/metacentrum/perun/core/api/GroupsManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/GroupsManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/GroupsManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupsManagerEntryIntegrationTest.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/GroupsManagerMethod.java
Labels: merge soon

#2364 Added use of checkAttributeSyntax
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
Labels: merge soon

#2371 CORE: Updated facility:virt:voShortNames module
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_virt_voShortNames.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/modules/attributes/FacilityVirtualAttributesModuleAbstract.java
Labels: waiting for review

#2375 New extSource TCS
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/InvalidCertificateException.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AttributesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceTCS.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/AttributesManagerImplApi.java
  perun-core/src/main/resources/perun-core.xml
Labels: merge soon, waiting for review

#2346 User sync failed events
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/UserManagerEvents/UserSyncFailed.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/UserManagerEvents/UserSyncFinishedWithErrors.java
Labels: waiting for review

#2376 Skipping of value check during dependencies check
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_virt_voShortNames.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_virt_denbiProjectMembers.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_virt_voShortName.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_attribute_def_virt_isSuspended.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_group_attribute_def_virt_isGroupAdmin.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_resource_attribute_def_virt_dataQuotas.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_resource_attribute_def_virt_fileQuotas.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_resource_attribute_def_virt_isBanned.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_resource_attribute_def_virt_voShortName.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_additionalIdentifiers.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_alternativeLoginNames.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_eduPersonEntitlement.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_eduPersonORCID.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_eduPersonPrincipalNames.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_eduPersonScopedAffiliations.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_epuids.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_groupNames.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_institutionsCountries.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_kerberosLogins.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_login_namespace_bbmri_persistent.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_login_namespace_bbmri_test_persistent.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_login_namespace_eduteams_acc_persistent.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_login_namespace_eduteams_persistent.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_login_namespace_einfraid_persistent.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_login_namespace_elixir_persistent.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_login_namespace_fenix_persistent.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_login_namespace_lifescienceid_persistent.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_login_namespace_westlife_persistent.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_logins_namespace_google.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_mails_namespace_google.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_openNebulaSSHAdminKeys.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_optionalLogin_namespace_mu.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_organizationsWithLoa.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_preferredPhone.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_schacHomeOrganizations.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_shibbolethExtSources.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_userCertDNs.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_userCertExpirations.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_userOrganizations.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_vomsDiracNickname.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_virt_blacklisted.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_virt_dataQuotas.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_virt_defaultUnixGID.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_virt_fileQuotas.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_virt_shell.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/modules/attributes/SkipValueCheckDuringDependencyCheck.java
  perun-core/src/test/java/cz/metacentrum/perun/core/bl/AttributesManagerBlImplUnitTests.java
Labels: merge soon

#2343 Removed virtual attribute value calculation from audit messages
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/AttributesManagerEvents/AttributeChangedForFacility.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/AttributesManagerEvents/AttributeChangedForResourceAndMember.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/AttributesManagerEvents/AttributeChangedForUser.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_virt_voShortNames.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_resource_attribute_def_virt_isBanned.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_groupNames.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_institutionsCountries.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_kerberosLogins.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_loa.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_userCertDNs.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/modules/attributes/UserVirtualAttributeCollectedFromUserExtSource.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_resource_attribute_def_virt_isBannedTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_eduPersonScopedAffiliationsTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_institutionsCountriesTest.java
Labels: merge soon

#2355 LDAPc AttributeProcessors changed: values of virtual attributes are getting from Perun
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/processor/impl/AbstractAttributeProcessor.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/processor/impl/FacilityAttributeProcessor.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/processor/impl/UserAttributeProcessor.java
  perun-ldapc/src/main/resources/perun-ldapc.xml
Labels: merge soon

#2352 Adding new role PERUNOBSERVER
  perun-base/src/main/java/cz/metacentrum/perun/core/api/Role.java
  perun-cabinet/src/main/java/cz/metacentrum/perun/cabinet/api/impl/CabinetManagerImpl.java
  perun-cli/setRole
  perun-cli/unsetRole
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/AttributesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ExtSourcesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/GroupsManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/SearcherEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/SecurityTeamsManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ServicesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/UsersManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/VosManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AuthzResolverImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/AuthzResolverImplApi.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/ConsolidatorManagerImpl.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
Labels: merge soon

#2379 (Un)SetRole privileges
  perun-base/src/main/java/cz/metacentrum/perun/core/impl/Privileges.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/AuthzResolver.java
  perun-core/src/test/java/cz/metacentrum/perun/core/api/AuthzResolverIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/PrivilegesTest.java
Labels: merge soon
