Repository CESNET/perun, pull requests merged in 2019-07, with the labels that each got.

#2317 Avoid of setting old quotas if new quotas are enabled on facility
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/AttributesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AttributesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_resource_attribute_def_def_dataLimit.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_resource_attribute_def_def_dataQuota.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_resource_attribute_def_def_filesLimit.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_resource_attribute_def_def_filesQuota.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_resource_attribute_def_def_defaultDataLimit.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_resource_attribute_def_def_defaultDataQuota.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_resource_attribute_def_def_defaultFilesLimit.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_resource_attribute_def_def_defaultFilesQuota.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/AttributesManagerImplApi.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/modules/attributes/MemberResourceAttributesModuleAbstract.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/modules/attributes/MemberResourceAttributesModuleImplApi.java
Labels: merge soon

#2310 Adding thrown exceptions to javadoc
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/GroupsManagerMethod.java
Labels: waiting for changes

#2316 New tool for updating application Form.
  perun-cli/Perun/Common.pm
  perun-cli/Perun/RegistrarAgent.pm
  perun-cli/Perun/beans/ApplicationForm.pm
  perun-cli/updateForm
Labels: merge soon

#2319 Adding methods to add member(s) to the group(s)
  perun-core/src/main/java/cz/metacentrum/perun/core/api/GroupsManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/GroupsManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/GroupsManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupsManagerEntryIntegrationTest.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/GroupsManagerMethod.java
Labels: merge soon

#2327 CORE: Make sure getUsersSubjects() doesn't get serialized to audit log
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/ExtSourceSimpleApi.java
Labels: merge soon

#2328 CORE: Use static ObjectMapper instance when storing audit messages
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Auditer.java
Labels: merge soon

#2329 Removing attributes minGID and maxGID
  perun-base/src/test/resources/test-data.sql
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_entityless_attribute_def_def_namespace_maxGID.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_entityless_attribute_def_def_namespace_minGID.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_virt_maxGID.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_virt_minGID.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_unixGID_namespace.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_resource_attribute_def_def_unixGID_namespace.java
Labels: merge soon

#2324 Optimalization of Attribute module user:virt:groupNames
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_groupNames.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_groupNamesTest.java
Labels: merge soon

#2332 CORE: Added check for null when removing opposite dependencies for attr
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
Labels: waiting for review
