Repository CESNET/perun, pull requests merged in 2019-03, with the labels that each got.

#2152 CORE: Fixed calculation expected membership expiration for GUI
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
Labels: waiting for review

#2094 Delete log from PerunException and PerunRuntimeException
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/PerunException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/rt/PerunRuntimeException.java
  perun-base/src/main/resources/logback-default.xml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/Api.java
Labels: waiting for review

#2169 CORE: Compare also large attributes before updating in DB
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AttributesManagerImpl.java
Labels: manual test needed

#1964 Group structure synchronization
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/GroupManagerEvents/GroupStructureSyncFailed.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/GroupManagerEvents/GroupStructureSyncFinishedWithErrors.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/CandidateGroup.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/CoreConfig.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/GroupStructureSynchronizationAlreadyRunningException.java
  perun-base/src/main/resources/perun-base.xml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/GroupsManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ExtSourcesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/GroupsManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ExtSourcesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/GroupsManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceCSV.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceEGISSO.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceGoogle.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceISMU.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceISXML.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceIdp.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceInternal.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceKerberos.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceLdap.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourcePerun.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceREMS.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceSql.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceUnity.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceVOOT.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceX509.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceXML.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/GroupsManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Synchronizer.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_flatGroupStructureEnabled.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_groupStructureSynchronizationEnabled.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_synchronizationEnabled.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/ExtSourceSimpleApi.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/GroupsManagerImplApi.java
  perun-core/src/main/resources/perun-core-synchronizers.xml
  perun-core/src/main/resources/perun-core.xml
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupStructureSynchronizationIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupsManagerEntryIntegrationTest.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/GroupsManagerMethod.java
Labels: merge soon
