Repository CESNET/perun, pull requests merged in 2019-04, with the labels that each got.

#2199 CORE: Call getConnection() in try-with-resources block
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/DatabaseManagerImpl.java
Labels: merge soon

#2180 Refactorization of method clearOld
  perun-base/src/main/java/cz/metacentrum/perun/controller/model/ServiceState.java
  perun-base/src/main/java/cz/metacentrum/perun/rpc/serializer/JsonSerializer.java
  perun-base/src/main/java/cz/metacentrum/perun/rpc/serializer/JsonSerializerGWT.java
  perun-base/src/main/java/cz/metacentrum/perun/rpc/serializer/JsonSerializerJSONP.java
  perun-base/src/main/java/cz/metacentrum/perun/rpc/serializer/JsonSerializerJSONSIMPLE.java
  perun-base/src/main/java/cz/metacentrum/perun/taskslib/model/Task.java
  perun-core/src/main/java/cz/metacentrum/perun/taskslib/dao/jdbc/TaskDaoJdbc.java
  perun-core/src/main/java/cz/metacentrum/perun/taskslib/dao/jdbc/TaskResultDaoJdbc.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/processing/EventProcessor.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/scheduling/PropagationMaintainer.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/scheduling/TaskScheduler.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/scheduling/impl/SchedulingPoolImpl.java
  perun-dispatcher/src/test/java/cz/metacentrum/perun/dispatcher/unit/SchedulingPoolTest.java
  perun-engine/src/main/java/cz/metacentrum/perun/engine/runners/GenCollector.java
  perun-engine/src/main/java/cz/metacentrum/perun/engine/runners/GenPlanner.java
  perun-engine/src/main/java/cz/metacentrum/perun/engine/runners/SendCollector.java
  perun-engine/src/main/java/cz/metacentrum/perun/engine/runners/SendPlanner.java
  perun-engine/src/main/java/cz/metacentrum/perun/engine/scheduling/impl/BlockingGenExecutorCompletionService.java
  perun-engine/src/main/java/cz/metacentrum/perun/engine/scheduling/impl/GenWorkerImpl.java
  perun-engine/src/main/java/cz/metacentrum/perun/engine/scheduling/impl/PropagationMaintainerImpl.java
  perun-engine/src/main/java/cz/metacentrum/perun/engine/scheduling/impl/SchedulingPoolImpl.java
  perun-engine/src/test/java/cz/metacentrum/perun/engine/AbstractEngineTest.java
  perun-engine/src/test/java/cz/metacentrum/perun/engine/unit/GenCollectorTest.java
  perun-engine/src/test/java/cz/metacentrum/perun/engine/unit/GenPlannerTest.java
  perun-engine/src/test/java/cz/metacentrum/perun/engine/unit/GenWorkerImplTest.java
Labels: waiting for changes

#2208 BASE,CORE: Auto-create namespaced attributes
  perun-base/src/main/java/cz/metacentrum/perun/core/api/CoreConfig.java
  perun-base/src/main/resources/perun-base.xml
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
Labels: waiting for review
