Repository CESNET/perun, pull requests merged in 2019-12, with the labels that each got.

#2488 fill LDAP attributes adminOf{Group,Facility,VO}
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/GroupsManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/beans/GroupSynchronizer.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/beans/UserSynchronizer.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/model/PerunAttribute.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/model/PerunGroup.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/model/PerunUser.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/model/PerunVO.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/model/impl/AbstractPerunEntry.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/model/impl/AttributeValueExtractor.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/model/impl/PerunAttributeDesc.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/model/impl/PerunFacilityImpl.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/model/impl/PerunGroupImpl.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/model/impl/PerunResourceImpl.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/model/impl/PerunUserImpl.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/processor/impl/FacilityAttributeProcessor.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/processor/impl/GroupEventProcessor.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/processor/impl/UserAttributeProcessor.java
  perun-ldapc/src/main/resources/perun-ldapc.xml
  perun-utils/ldapc-scripts/schemas/perun-schema.ldif
Labels: merge soon, waiting for review

#2512 LDAPC: Push also eduPersonEntitlement to the LDAP
  perun-ldapc/src/main/resources/perun-ldapc.xml
  perun-utils/ldapc-scripts/schemas/perun-schema.ldif
Labels: merge soon

#2517 CABINET: Added method to find users publications by filter
  perun-cabinet/src/main/java/cz/metacentrum/perun/cabinet/api/CabinetManager.java
  perun-cabinet/src/main/java/cz/metacentrum/perun/cabinet/api/impl/CabinetManagerImpl.java
  perun-cabinet/src/main/java/cz/metacentrum/perun/cabinet/bl/PublicationManagerBl.java
  perun-cabinet/src/main/java/cz/metacentrum/perun/cabinet/bl/impl/PublicationManagerBlImpl.java
  perun-cabinet/src/main/java/cz/metacentrum/perun/cabinet/dao/PublicationManagerDao.java
  perun-cabinet/src/main/java/cz/metacentrum/perun/cabinet/dao/impl/PublicationManagerDaoImpl.java
  perun-cli/Perun/CabinetAgent.pm
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/CabinetManagerMethod.java
Labels: merge soon

#2501 Tests for AuthzResolver.authorized() method
  perun-base/src/test/resources/perun-roles.yml
  perun-core/src/test/java/cz/metacentrum/perun/core/api/AuthzResolverIntegrationTest.java
Labels: waiting for review
