Repository CESNET/perun, pull requests merged in 2019-02, with the labels that each got.

#2120 Tools for managin SpecificUsers
  perun-cli/Perun/UsersAgent.pm
  perun-cli/addSpecificUserOwner
  perun-cli/getSpecificUsersByUser
  perun-cli/getUsersBySpecificUser
  perun-cli/removeSpecificUserOwner
  perun-cli/setSpecificUser
  perun-cli/unsetSpecificUser
Labels: merge soon

#2127 New way how to work with IN clause in OracleDB
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/java/cz/metacentrum/perun/core/api/AttributesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/DatabaseManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/DatabaseManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AttributesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Compatibility.java
  perun-core/src/main/resources/hsqldbChangelog.txt
  perun-core/src/main/resources/oracleChangelog.txt
  perun-core/src/main/resources/postgresChangelog.txt
  perun-db/oracle.sql
  perun-db/postgres.sql
Labels: waiting for changes

#2121 Fix wrong using of namespace in defaultUnixGID module
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_virt_defaultUnixGID.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_virt_defaultUnixGIDTest.java
Labels: merge soon, waiting for review

#2136 Refactorization of getActiveUserExtSources
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/UsersManagerImpl.java
Labels: merge soon

#2134 Refactorization of isMemberInGracePeriod
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
Labels: merge soon
