Repository CESNET/perun, pull requests merged in 2020-11, with the labels that each got.

#2972 CORE: Removed module for unused login-namespace:kypo
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_kypo.java
Labels: merge soon

#2973 CORE: Fixed DB changelog for 3.1.68
  perun-core/src/main/resources/postgresChangelog.txt
Labels: merge soon

#2974 New attributes rpEnvironment and rpProtocol
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_rpEnvironment.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_rpProtocol.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_rpEnvironmentTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_rpProtocolTest.java
  perun-ldapc/src/main/resources/perun-ldapc.xml
  perun-utils/ldapc-scripts/schemas/perun-schema.ldif
Labels: merge soon

#2969 Methods for convertion of sponsored users
  perun-core/src/main/java/cz/metacentrum/perun/core/api/VosManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/VosManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/VosManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/VosManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/VosManagerEntryIntegrationTest.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/VosManagerMethod.java
Labels: waiting for review

#2976 Unique sponsorship between member and user
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/MembersManagerImpl.java
  perun-core/src/main/resources/hsqldbChangelog.txt
  perun-core/src/main/resources/postgresChangelog.txt
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/MembersManagerEntryIntegrationTest.java
  perun-db/postgres.sql
Labels: waiting for review

#2978 Throw AlreadySponsorException where needed
  perun-core/src/main/java/cz/metacentrum/perun/core/api/MembersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/MembersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/MembersManagerImplApi.java
Labels: merge soon

#2979 add new JSONLITE serializer to rpc
  perun-base/src/main/java/cz/metacentrum/perun/rpc/serializer/JsonSerializerJSONLITE.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/Api.java
Labels: waiting for review

#2975 Refactorization of automatic rejection of applications
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/SearcherBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/SearcherBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/SearcherImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/SearcherImplApi.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/AppAutoRejectionScheduler.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/ExpirationNotifScheduler.java
  perun-registrar-lib/src/main/resources/perun-registrar-lib-scheduler.xml
  perun-registrar-lib/src/main/resources/perun-registrar-lib.xml
  perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/AppAutoRejectionSchedulerTest.java
  perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/ExpirationNotifSchedulerTest.java
Labels: waiting for review

#2977 General getAdmins methods
  perun-base/src/main/java/cz/metacentrum/perun/core/api/RoleManagementRules.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/RoleCannotBeManagedException.java
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/AuthzResolver.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AuthzResolverImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunRolesLoader.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/AuthzResolverImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/api/AuthzResolverIntegrationTest.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/AuthzResolverMethod.java
Labels: waiting for review

#2987 method for getting roles management rules
  perun-core/src/main/java/cz/metacentrum/perun/core/api/AuthzResolver.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AuthzResolverImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunPoliciesContainer.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/AuthzResolverMethod.java
Labels: waiting for review

#2991 CORE: Prevent tests to run twice for AttributesManager
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/AttributesManagerEntryIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/AttributesManagerEntryIntegrationTestAbstract.java
Labels: merge soon

#2990 CORE: Prevent group name collisions for top-level groups
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/resources/hsqldbChangelog.txt
  perun-core/src/main/resources/postgresChangelog.txt
  perun-db/postgres.sql
Labels: merge soon

#2988 CORE: Support large attributes in getUsersByAttributeValue()
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/UsersManagerImpl.java
Labels: merge soon, waiting for review

#2993 Fix roles management
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/ApiCaller.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/AuthzResolverMethod.java
Labels: waiting for review

#2999 Extend role management rules
  perun-base/src/main/java/cz/metacentrum/perun/core/api/RoleManagementRules.java
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunRolesLoader.java
  perun-openapi/openapi.yml
Labels: waiting for review

#2996 Extend and refactor sending of validation requests in Utils
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
Labels: merge soon

#3002 CORE: Removed unused default_attr_id column from attr_names table
  perun-base/src/test/resources/test-data.sql
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/resources/hsqldbChangelog.txt
  perun-core/src/main/resources/postgresChangelog.txt
  perun-db/postgres.sql
Labels: merge soon

#3000 Core - createSponsoredMembersFromCSV
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/MembersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/MembersManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/MembersManagerMethod.java
Labels: waiting for review

#3001 new perun-auditlogger component
  perun-auditlogger/pom.xml
  perun-auditlogger/src/main/java/cz/metacentrum/perun/auditlogger/logger/EventLogger.java
  perun-auditlogger/src/main/java/cz/metacentrum/perun/auditlogger/logger/impl/EventLoggerImpl.java
  perun-auditlogger/src/main/java/cz/metacentrum/perun/auditlogger/main/AuditLoggerStarter.java
  perun-auditlogger/src/main/java/cz/metacentrum/perun/auditlogger/service/AuditLoggerManager.java
  perun-auditlogger/src/main/java/cz/metacentrum/perun/auditlogger/service/impl/AuditLoggerManagerImpl.java
  perun-auditlogger/src/main/resources/logback.xml
  perun-auditlogger/src/main/resources/perun-auditlogger.xml
  perun-utils/init.d-scripts/perun-auditlogger.debian
  perun-utils/systemd/perun-auditlogger.service
  pom.xml
Labels: merge soon
