Repository CESNET/perun, pull requests merged in 2020-04, with the labels that each got.

#2650 LDAPC: Support for Vo/Group attribute event processing
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/beans/GroupSynchronizer.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/beans/VOSynchronizer.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/model/PerunGroup.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/model/PerunVO.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/model/impl/PerunGroupImpl.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/model/impl/PerunVOImpl.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/processor/impl/GroupAttributeProcessor.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/processor/impl/UserAttributeProcessor.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/processor/impl/VoAttributeProcessor.java
  perun-ldapc/src/main/resources/perun-ldapc.xml
Labels: merge soon

#2525 New authorization in DatabaseManagerEntry
  perun-base/src/test/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/DatabaseManagerEntry.java
Labels: merge soon

#2529 New authorization in ExtSourceManagerEntry
  perun-base/src/test/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ExtSourcesManagerEntry.java
Labels: merge soon

#2526 New authorization in OwnersManagerEntry
  perun-base/src/test/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/OwnersManagerEntry.java
Labels: merge soon

#2524 New authorization in AuditMessagesManagerEntry
  perun-base/src/test/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/AuditMessagesManagerEntry.java
Labels: merge soon

#2592 New authorization in SecurityTeamsManagerEntry
  perun-base/src/test/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/SecurityTeamsManagerEntry.java
Labels: merge soon

#2653 CORE,GUI: Removed references to unused member:opt:eduPersonAffiliation
  perun-base/src/test/resources/test-data.sql
  perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/RegistrarBaseIntegrationTest.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/memberstabs/MemberOverviewTabItem.java
Labels: merge soon

#2657 CORE: Fixed dao layer of getAttributes(sess, group, attrNames)
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AttributesManagerImpl.java
Labels: merge soon

#2655 CORE: Fixed virt attr value changed for user:virt:groupNames
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_groupNames.java
Labels: merge soon

#2654 REGISTRAR: Removed usage of member:virt:loa from module Elixircz
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/Elixircz.java
Labels: merge soon

#2658 GUI: Use user:virt:loa instead of member version
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/memberstabs/MemberOverviewTabItem.java
Labels: merge soon

#2656 Added method to reactivate member in group
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/GroupsManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupsManagerEntryIntegrationTest.java
Labels: merge soon

#2652 Created attribute definitions for member profile
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
Labels: merge soon

#2665 LDAPC: Push resource:def:isAssignedWithSubgroups to LDAP
  perun-ldapc/src/main/resources/perun-ldapc.xml
  perun-utils/ldapc-scripts/schemas/perun-schema.ldif
Labels: merge soon

#2664 Use reactivation of member for group trigger
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
Labels: merge soon

#2667 Fix wrong check of membership in reactivation process
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
Labels: merge soon, waiting for review

#2666 REGISTRAR: More robust mail validation
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/MailManagerImpl.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
Labels: merge soon

#2661 Multiple Identifiers with shibIdentityProvider
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/PerunBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/PerunBlImpl.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/Api.java
Labels: merge soon

#2670 added voobserver to findMembers methods
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
Labels: waiting for review

#2671 CORE: Fixed audit message resolving for eduPersonScopedAffiliations
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/MembersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_eduPersonScopedAffiliations.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/MembersManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_eduPersonScopedAffiliationsTest.java
Labels: merge soon

#2669 RTMessagesManager was added to OpenApi
  perun-openapi/openapi.yml
Labels: waiting for review

#2673 removeUserExtSource method was added to OpenApi
  perun-openapi/openapi.yml
Labels: waiting for review

#2631 OpenApi - getRequiredAttributes
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/AttributesManagerMethod.java
Labels: waiting for review

#2674 CORE: Do not recompile patterns on each check
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ModulesUtilsBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ModulesUtilsBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_unixGroupName_namespace.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_resource_attribute_def_def_unixGroupName_namespace.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_fedcloud.java
Labels: merge soon, waiting for review
