Repository CESNET/perun, pull requests merged in 2020-09, with the labels that each got.

#2874 Extended rights for PERUNOBSERVER role
  perun-base/src/main/resources/perun-roles.yml
Labels: waiting for review

#2872 Optimize memory usage in Agent.pm
  perun-cli/Perun/Agent.pm
Labels: waiting for review

#2864 Fix too long processing of members in the tree of groups
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
Labels: merge soon

#2847 New method to convert unique attribute to nonunique
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/AttributeNotMarkedUniqueException.java
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/AttributesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/AttributesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/AttributesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AttributesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/AttributesManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/AttributesManagerEntryIntegrationTestAbstract.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/AttributesManagerMethod.java
Labels: merge soon

#2876 Added getUsersSubjects to ExtSources
  perun-core/src/main/java/cz/metacentrum/perun/core/api/UsersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceCSV.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceEGISSO.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceGoogle.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceISMU.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceLdap.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourcePerun.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceREMS.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceSql.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceTCS.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceUnity.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceVOOT.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceXML.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/ExtSourceCSVTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/ExtSourceEGISSOTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/ExtSourceGoogleTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/ExtSourceISMUTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/ExtSourceLdapTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/ExtSourcePerunTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/ExtSourceREMSTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/ExtSourceSqlTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/ExtSourceTCSTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/ExtSourceUnityTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/ExtSourceVOOTTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/ExtSourceXMLTest.java
Labels: waiting for review

#2871 Core - new method to gen data
  perun-base/src/main/java/cz/metacentrum/perun/core/api/GenDataNode.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/GenMemberDataNode.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/HashedGenData.java
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/ServicesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/AttributesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ServicesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ServicesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ServicesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AttributesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/AttributesManagerImplApi.java
  perun-core/src/main/java/cz/metacentrum/perun/core/provisioning/GenDataProvider.java
  perun-core/src/main/java/cz/metacentrum/perun/core/provisioning/GenDataProviderImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/provisioning/GroupsHashedDataGenerator.java
  perun-core/src/main/java/cz/metacentrum/perun/core/provisioning/HashedDataGenerator.java
  perun-core/src/main/java/cz/metacentrum/perun/core/provisioning/Hasher.java
  perun-core/src/main/java/cz/metacentrum/perun/core/provisioning/HierarchicalHashedDataGenerator.java
  perun-core/src/main/java/cz/metacentrum/perun/core/provisioning/IdHasher.java
  perun-core/src/main/resources/perun-core.xml
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/AttributesManagerEntryIntegrationTestAbstract.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/ServicesManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ServicesManagerMethod.java
Labels: waiting for review

#2885 Fixed calling of authorization
  perun-cabinet/src/main/java/cz/metacentrum/perun/cabinet/api/impl/CabinetManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/GroupsManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ServicesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/UsersManagerEntry.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/MailManagerImpl.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
Labels: waiting for review

#2838 Fix invalid entry calls
  perun-base/src/main/resources/perun-roles.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/AttributesManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ExtSourcesManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/FacilitiesManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/GroupsManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/MembersManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/OwnersManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ResourcesManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ServicesManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/UsersManagerMethod.java
Labels: merge soon

#2875 Core - created display name heuristic
  perun-registrar-lib/pom.xml
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
  perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImplUnitTest.java
Labels: merge soon

#2880 Core - new method to create service user
  perun-base/src/main/java/cz/metacentrum/perun/core/api/Candidate.java
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/UsersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/UsersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/UsersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/UsersManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/UsersManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/UsersManagerMethod.java
Labels: merge soon

#2886 Exclusion of uco based emails from o365 mu attribute modules
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_o365EmailAddresses_o365mu.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_resource_attribute_def_def_o365EmailAddresses_mu.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_o365UserEmailAddresses_mu.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_o365EmailAddresses_o365muTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_resource_attribute_def_def_o365EmailAddresses_muTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_o365UserEmailAddresses_muTest.java
Labels: waiting for review

#2889 add OpenAPI: methods and added role to getRichAdmins
  perun-core/src/main/java/cz/metacentrum/perun/core/api/VosManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/VosManagerEntry.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/VosManagerMethod.java
Labels: waiting for changes, waiting for review

#2895 Core - bug fix
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/MembersManagerImpl.java
Labels: bug, waiting for review

#2898 Core - Duplicate candidates
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/VosManagerBlImpl.java
  perun-core/src/test/java/cz/metacentrum/perun/core/bl/VosManagerBlImplUnitTest.java
Labels: waiting for changes

#2896 Filter of groups where member is direct in addMember moved to entry
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/GroupsManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupsManagerEntryIntegrationTest.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/GroupsManagerMethod.java
Labels: waiting for review

#2893 Core - Member mapper rework
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/GroupsManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/MembersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ResourcesManagerImpl.java
Labels: waiting for review

#2855 Ldap attribute fix
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/model/PerunAttribute.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/model/impl/PerunUserImpl.java
  perun-utils/ldapc-scripts/schemas/perun-schema.ldif
Labels: merge soon

#2899 Fixed rights for GroupAdmin
  perun-base/src/main/resources/perun-roles.yml
Labels: waiting for review

#2900 New LDAP attribute schacPersonalUniqueCode
  perun-base/src/main/java/cz/metacentrum/perun/core/api/CoreConfig.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_schacPersonalUniqueCodes.java
  perun-ldapc/src/main/resources/perun-ldapc.xml
  perun-utils/ldapc-scripts/schemas/perun-schema.ldif
Labels: merge soon

#2891 Core - enrichedResource
  perun-base/src/main/java/cz/metacentrum/perun/core/api/EnrichedResource.java
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/ResourcesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ResourcesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ResourcesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ResourcesManagerMethod.java
Labels: waiting for review

#2901 ENGINE: Added WARNING state for the Task and TaskResult
  perun-auditparser/src/main/java/cz/metacentrum/perun/auditparser/AuditParser.java
  perun-base/src/main/java/cz/metacentrum/perun/taskslib/model/SendTask.java
  perun-base/src/main/java/cz/metacentrum/perun/taskslib/model/Task.java
  perun-base/src/main/java/cz/metacentrum/perun/taskslib/model/TaskResult.java
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/TasksManagerImpl.java
  perun-core/src/main/resources/hsqldbChangelog.txt
  perun-core/src/main/resources/postgresChangelog.txt
  perun-db/postgres.sql
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/scheduling/PropagationMaintainer.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/scheduling/impl/SchedulingPoolImpl.java
  perun-engine/src/main/java/cz/metacentrum/perun/engine/runners/SendCollector.java
  perun-engine/src/main/java/cz/metacentrum/perun/engine/scheduling/impl/PropagationMaintainerImpl.java
  perun-engine/src/main/java/cz/metacentrum/perun/engine/scheduling/impl/SchedulingPoolImpl.java
  perun-engine/src/main/java/cz/metacentrum/perun/engine/scheduling/impl/SendWorkerImpl.java
  perun-openapi/openapi.yml
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/tasksManager/GetFacilityServicesState.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/tasksManager/GetFacilityState.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/tasksManager/GetRichTaskResultsByTask.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/tasksManager/GetRichTaskResultsByTaskAndDestination.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/tasksManager/GetTaskResultsByDestinations.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/vostabs/VoResourcesPropagationsTabItem.java
Labels: merge soon

#2904 Removed subgroups as child elements from getDataWithGroups
  perun-core/src/main/java/cz/metacentrum/perun/core/api/ServicesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ServicesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ServicesManagerBlImpl.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ServicesManagerMethod.java
Labels: waiting for review

#2887 Removed functionality for creating sponsored users
  perun-core/src/main/java/cz/metacentrum/perun/core/api/MembersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/UsersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/UsersManagerEntryIntegrationTest.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/MembersManagerMethod.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/memberstabs/CreateServiceMemberInVoTabItem.java
Labels: waiting for review

#2890 Core - UUID
  perun-auditparser/src/main/java/cz/metacentrum/perun/auditparser/AuditParser.java
  perun-auditparser/src/test/java/cz/metacentrum/perun/auditparser/AuditParserTest.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/Group.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/HasUUID.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/Resource.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/RichGroup.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/RichResource.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/RichUser.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/User.java
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/GroupsManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ResourcesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/UsersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/GroupsManagerImplApi.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/ResourcesManagerImplApi.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/UsersManagerImplApi.java
  perun-core/src/main/resources/hsqldbChangelog.txt
  perun-core/src/main/resources/postgresChangelog.txt
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupsManagerEntryIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntryIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/UsersManagerEntryIntegrationTest.java
  perun-db/postgres.sql
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
Labels: merge soon

#2908 GUI - new format of audit messages
  perun-base/src/main/java/cz/metacentrum/perun/core/api/AuditMessage.java
  perun-base/src/main/java/cz/metacentrum/perun/rpc/deserializer/JsonDeserializer.java
  perun-base/src/main/java/cz/metacentrum/perun/rpclib/impl/JsonDeserializer.java
  perun-base/src/main/java/cz/metacentrum/perun/rpclib/impl/JsonSerializer.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/auditMessagesManager/GetAuditMessagesByCount.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/model/AuditMessage.java
Labels: merge soon

#2909 CORE: Fixed SQL when preparing query for users with exact match
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
Labels: bug, merge soon

#2906 Core - auto extension of members
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_vo_attribute_def_def_membershipExpirationRules.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/modules/attributes/AbstractMembershipExpirationRulesModule.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_vo_attribute_def_def_membershipExpirationRulesTest.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/ExpirationNotifScheduler.java
  perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/ExpirationNotifSchedulerTest.java
Labels: merge soon
