Repository CESNET/perun, pull requests merged in 2020-08, with the labels that each got.

#2802 CORE: All attribute tables now have single attr_value column
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/FacilitiesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AttributesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/SearcherImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/AttributesManagerImplApi.java
  perun-core/src/main/resources/hsqldbChangelog.txt
  perun-core/src/main/resources/postgresChangelog.txt
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/AttributesManagerEntryIntegrationTestAbstract.java
  perun-db/postgres.sql
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/attributestabs/AttributeDefinitionDetailTabItem.java
Labels: merge soon

#2829 RPC: Removed deprecated API checkAttributeValue()
  perun-cli/Perun/AttributesAgent.pm
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/AttributesManagerMethod.java
Labels: merge soon

#2821 CORE,RPC,GUI: Support for TaskResults deletion from GUI
  perun-core/src/main/java/cz/metacentrum/perun/core/api/TasksManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/TasksManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/FacilitiesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/TasksManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/TasksManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/TasksManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/TasksManagerImplApi.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/service/impl/DispatcherManagerImpl.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/TasksManagerMethod.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/client/UiElements.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/tasksManager/DeleteTaskResults.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/tasksManager/GetRichTaskResultsByTask.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/tasksManager/GetRichTaskResultsByTaskAndDestination.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/model/TaskResult.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/facilitiestabs/TaskResultsForDestinationTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/facilitiestabs/TaskResultsTabItem.java
Labels: merge soon

#2832 LDAPC: Removed logic to store facility attributes on resource
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/processor/impl/CreationEventProcessor.java
Labels: merge soon

#2836 New modules and tests for attributes
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_adName_o365mu.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_o365EmailAddresses_o365mu.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_adName_o365muTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_o365EmailAddresses_o365muTest.java
Labels: waiting for review

#2835 REGISTRAR: Generate links with ? instead of #
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/MailManagerImpl.java
Labels: merge soon

#2826 Change of lightweightSynchronization to not add members not in Perun
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
Labels: waiting for review

#2843 Fixed rights for top group creator
  perun-base/src/main/resources/perun-roles.yml
Labels: waiting for review

#2846 Resource admins euthz extension
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AuthzResolverImpl.java
Labels: merge soon

#2831 Edit of findUsers
  perun-base/src/main/java/cz/metacentrum/perun/core/api/CoreConfig.java
  perun-base/src/main/resources/perun-base.xml
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/MembersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/UsersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/MembersManagerImplApi.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/UsersManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/MembersManagerEntryIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/UsersManagerEntryIntegrationTest.java
Labels: merge soon

#2845 Perun roles documentation
  perun-base/src/main/resources/perun-roles.yml
Labels: waiting for review

#2850 BASE: Removed unused getter/setter for cache enabled config option
  perun-base/src/main/java/cz/metacentrum/perun/core/api/CoreConfig.java
Labels: merge soon

#2839 Change of behavior in module m:d:o365EmailAddresses:mu
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_attribute_def_def_o365EmailAddresses_mu.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_attribute_def_def_o365EmailAddresses_muTest.java
Labels: don't merge, waiting for review

#2842 Fixh authz for rich objets
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
Labels: waiting for review

#2852 stringToMapOfAttributes will return empty map
  perun-base/src/main/java/cz/metacentrum/perun/core/api/BeansUtils.java
Labels: waiting for review

#2853 Replaced isAuthorized in other perun layers
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/AuthzResolverMethod.java
Labels: merge soon

#2857 LifeScience persistent shadow attribute
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_lifescienceid_persistent_shadow.java
Labels: waiting for review

#2797 Change of transaction over synchronizeGroup
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/resources/perun-core.xml
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupAndGroupStructureSynchronizationIntegrationTest.java
Labels: manual test needed

#2856 Core - new overloaded version of authorizedInternal
  perun-core/src/main/java/cz/metacentrum/perun/core/api/AuthzResolver.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/AttributesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ExtSourcesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/GroupsManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/OwnersManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/SearcherEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/SecurityTeamsManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ServicesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/TasksManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/UsersManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/VosManagerEntry.java
Labels: waiting for review

#2861 Extend RESOURCEADMIN privileges
  perun-base/src/main/resources/perun-roles.yml
Labels: waiting for review

#2841 New authorization in other Perun modules
  perun-base/src/main/resources/perun-roles.yml
  perun-cabinet/src/main/java/cz/metacentrum/perun/cabinet/api/impl/CabinetManagerImpl.java
  perun-cabinet/src/main/java/cz/metacentrum/perun/cabinet/bl/impl/PublicationManagerBlImpl.java
  perun-notification/src/main/java/cz/metacentrum/perun/notif/managers/PerunNotifNotificationManagerImpl.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/RegistrarManager.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/ConsolidatorManagerImpl.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/MailManagerImpl.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
Labels: waiting for review

#2863 Authz extended for RESOURCESELFSERVICE
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/GroupsManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntry.java
Labels: waiting for review

#2867 VOOBSERVER cannot make VOOBSERVER
  perun-base/src/main/resources/perun-roles.yml
Labels: waiting for review

#2873 Extended rights for VOOBSERVER role
  perun-base/src/main/resources/perun-roles.yml
Labels: waiting for review
