Repository CESNET/perun, pull requests merged in 2020-07, with the labels that each got.

#2777 Openapi
  perun-openapi/openapi.yml
Labels: waiting for review

#2773 CORE: Move generating random password into PasswordManagerModule
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/UsersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/DummyPasswordManagerModule.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/GenericPasswordManagerModule.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/MuPasswordManagerModule.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/VsupPasswordManagerModule.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/modules/pwdmgr/PasswordManagerModule.java
Labels: merge soon

#2774 Modification of group structure synchronization
  perun-core/src/main/java/cz/metacentrum/perun/core/api/GroupsManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ExtSourcesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ExtSourcesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupStructureSynchronizationIntegrationTest.java
Labels: merge soon

#2775 New method forceAllSubGroupsSynchronization
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/GroupSynchronizationNotEnabledException.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/GroupsManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/GroupsManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/GroupsManagerEntry.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/GroupsManagerMethod.java
Labels: waiting for changes, waiting for review

#2591 New authorization in TasksManagerEntry
  perun-base/src/test/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/TasksManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/TasksManagerEntry.java
Labels: waiting for review

#2779 CORE: Do not double "name" param in serialized AuditEvent
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/AuditEvent.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/GroupManagerEvents/GroupMoved.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/VoManagerEvents/VoUpdated.java
Labels: merge soon

#2780 Fixed definition of OpenAPI method getBansForFacility
  perun-openapi/openapi.yml
Labels: waiting for review

#2528 New authorization in SearcherEntry
  perun-base/src/test/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/Searcher.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/SearcherEntry.java
Labels: waiting for review

#2776 Group structure sync - resources
  perun-base/src/main/java/cz/metacentrum/perun/core/api/BeansUtils.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_groupStructureResources.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupStructureSynchronizationIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_groupStructureResourcesTest.java
Labels: waiting for review

#2772 OpenApi - getAssignedRichResources
  perun-openapi/openapi.yml
Labels: waiting for review

#2781 CORE: Allow SELF role to read/write on Resource attributes
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
Labels: merge soon

#2611 New authorization in ServicesManagerEntry
  perun-base/src/test/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ServicesManagerEntry.java
Labels: waiting for review

#2609 New authorization in UsersManagerEntry
  perun-base/src/test/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/UsersManagerEntry.java
Labels: waiting for review

#2621 New authorization in FacilitiesManagerEntry
  perun-base/src/test/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/FacilitiesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntry.java
Labels: waiting for review

#2493 Replaced old authorization by the new one in VosManagerEntry
  perun-base/src/test/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/VosManagerEntry.java
Labels: waiting for review

#2782 CORE: Converted all char(1) columns not named 'status' to boolean
  perun-base/src/test/resources/test-data.sql
  perun-base/src/test/resources/test-schema.sql
  perun-cabinet/src/main/java/cz/metacentrum/perun/cabinet/dao/impl/PublicationManagerDaoImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Compatibility.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/MembersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ServicesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/UsersManagerImpl.java
  perun-core/src/main/resources/hsqldbChangelog.txt
  perun-core/src/main/resources/postgresChangelog.txt
  perun-db/postgres.sql
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/MailManagerImpl.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
Labels: merge soon

#2616 New authorization in GroupsManagerEntry
  perun-base/src/test/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/GroupsManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/GroupsManagerEntry.java
Labels: waiting for review

#2784 CORE: Simplified reading of attribute value
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AttributesManagerImpl.java
Labels: merge soon

#2787 Fix authorization -getPendingPreferredEmailChanges
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/UsersManagerEntry.java
Labels: waiting for review

#2786 Attributes cache removed
  perun-base/pom.xml
  perun-base/src/main/java/cz/metacentrum/perun/core/api/AttributeHolders.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/AttributeIdWithHolders.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/AttributeIdWithHoldersTransformer.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/BeansUtils.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/Holder.java
  perun-base/src/main/resources/perun-base.xml
  perun-core/pom.xml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/Perun.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/PerunBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AttributesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/CacheManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunBasicDataSource.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunConnection.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunTestTransactionManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunTransactionManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/AttributesManagerImplApi.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/CacheManagerApi.java
  perun-core/src/main/resources/infinispan-config.xml
  perun-core/src/main/resources/perun-core.xml
  perun-core/src/test/java/cz/metacentrum/perun/core/AbstractPerunIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/AttributesManagerEntryIntegrationCacheTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/CacheManagerTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/CacheManagerTransactionsTest.java
  perun-scim/src/main/java/cz/metacentrum/perun/scim/api/entities/UserSCIM.java
Labels: waiting for review

#2791 CORE: Keep last_access timestamp when moving UserExtSource
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/UsersManagerImpl.java
Labels: merge soon

#2792 CORE: Handle members.status as integer
  perun-base/src/main/java/cz/metacentrum/perun/core/api/Status.java
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/FacilitiesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/GroupsManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/MembersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ResourcesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/UsersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_groupNames.java
  perun-core/src/main/resources/hsqldbChangelog.txt
  perun-core/src/main/resources/postgresChangelog.txt
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_groupNamesTest.java
  perun-db/postgres.sql
Labels: merge soon

#2726 Added new object EnrichedHost and new method getEnrichedHosts
  perun-base/src/main/java/cz/metacentrum/perun/core/api/EnrichedHost.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/AttributesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/FacilitiesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/AttributesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/AttributesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AttributesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/AttributesManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/AttributesManagerEntryIntegrationTestAbstract.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/AttributesManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/FacilitiesManagerMethod.java
Labels: waiting for review

#2625 isAuthorized method Deprecated
  perun-core/src/main/java/cz/metacentrum/perun/core/api/AuthzResolver.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
Labels: merge soon

#2788 New method in Core - get policies
  perun-core/src/main/java/cz/metacentrum/perun/core/api/AuthzResolver.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AuthzResolverImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunPoliciesContainer.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/AuthzResolverMethod.java
Labels: waiting for review

#2795 GUI - secondary group name regex
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/groupstabs/CreateGroupTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/groupstabs/EditGroupDetailsTabItem.java
Labels: merge soon

#2643 New authorization in ResourcesManagerEntry
  perun-base/src/test/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/ResourcesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntry.java
Labels: waiting for changes

#2499 Added RoleManagementRules
  perun-base/src/main/java/cz/metacentrum/perun/core/api/RoleManagementRules.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/RoleManagementRulesNotExistsException.java
  perun-base/src/test/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AuthzResolverImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunPoliciesContainer.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunRolesLoader.java
Labels: merge soon, waiting for changes

#2798 CORE: Removed all unused "status" columns
  perun-base/src/test/resources/test-data.sql
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AuthzResolverImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/UsersManagerImpl.java
  perun-core/src/main/resources/hsqldbChangelog.txt
  perun-core/src/main/resources/postgresChangelog.txt
  perun-db/postgres.sql
Labels: merge soon

#2672 additional identifiers support in RegistrarModule
  perun-base/src/main/java/cz/metacentrum/perun/core/api/BeansUtils.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/AuthzResolver.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/PerunBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/UsersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/PerunBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/UsersManagerBlImpl.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/RegistrarManager.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/ConsolidatorManagerImpl.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/MailManagerImpl.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/Api.java
Labels: waiting for review

#2645 New authorization in AuthzResolver
  perun-base/src/test/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/AuthzResolver.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
Labels: merge soon, waiting for changes

#2790 DISPATCHER: Reintroduced configurable re-schedule interval
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/scheduling/PropagationMaintainer.java
  perun-dispatcher/src/main/resources/perun-dispatcher.xml
Labels: merge soon

#2801 fix for OpenAPI
  perun-openapi/openapi.yml
Labels: waiting for review

#2796 Added openapi definition for updateGroup method
  perun-openapi/openapi.yml
Labels: waiting for review

#2804 Openapi update
  perun-openapi/openapi.yml
Labels: waiting for review

#2806 RPC: Bumped tomcat and cargo plugin to latest version
  perun-rpc/pom.xml
  perun-rpc/tomcat.xml
  pom.xml
Labels: merge soon

#2805 GUI: Bumped GWT version to 2.9.0
  perun-web-gui/pom.xml
Labels: merge soon

#2809 OpenAPI specificUser
  perun-openapi/openapi.yml
Labels: waiting for review

#2808 updateForm openapi method input parameter fixed
  perun-openapi/openapi.yml
Labels: waiting for review

#2803 GUI: Introduce password strength check for presence of login
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/client/resources/Utils.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/memberstabs/CreateServiceMemberInVoTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/userstabs/SelfPasswordTabItem.java
Labels: merge soon

#2812 new method submitApplication
  perun-openapi/openapi.yml
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/RegistrarManager.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/RegistrarManagerMethod.java
Labels: merge soon

#2813 OpenAPI member groups
  perun-openapi/openapi.yml
Labels: waiting for review

#2624 New authorization in MembersManagerEntry
  perun-base/src/test/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/MembersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
Labels: waiting for changes, waiting for review

#2799 Core - search users optimizations
  perun-core/src/main/java/cz/metacentrum/perun/core/api/AuthzResolver.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/UsersManagerBlImpl.java
Labels: merge soon

#2746 Updated methods in FacilitiesManagerMethod to work with facilityName
  perun-base/src/test/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/FacilitiesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/OwnersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/OwnersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/OwnersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/OwnersManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/OwnersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/OwnersManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntryIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/OwnersManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/ApiCaller.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/FacilitiesManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/OwnersManagerMethod.java
Labels: merge soon

#2815 New authorization in AttributesManagerEntry
  perun-base/src/test/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/AttributesManagerEntry.java
Labels: merge soon, waiting for review

#2817 OpenAPI getUsersBySpecificUser
  perun-openapi/openapi.yml
Labels: waiting for review

#2816 Roles - default politics file
  perun-base/src/main/java/cz/metacentrum/perun/core/api/PerunPolicy.java
  perun-base/src/main/resources/perun-roles.yml
  perun-base/src/test/resources/test-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AuthzResolverImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunPoliciesContainer.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunRolesLoader.java
  perun-core/src/main/resources/perun-core.xml
Labels: merge soon

#2818 CORE: Entityless attributes must be marked as writable
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/AttributesManagerEntry.java
Labels: merge soon

#2819 GUI: Fixed entityless attributes editing
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/client/resources/PerunEntity.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/GetEntityById.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/attributesManager/GetEntitylessAttributes.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/keyproviders/EntitylessAttributeKeyProvider.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/model/Attribute.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/AttributesTabs.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/entitylessattributestabs/EntitylessAttributeEditKeyTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/widgets/cells/PerunAttributeValueCell.java
Labels: merge soon

#2824 CORE: Use case insensitive comparing in attribute tcsMails:mu
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_tcsMails_mu.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_tcsMails_muTest.java
Labels: merge soon

#2823 CORE: Simplified and fixed einfra password check
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/EinfraPasswordManagerModule.java
Labels: merge soon

#2828 validateMemberAsync method definition added to OpenAPI
  perun-openapi/openapi.yml
Labels: waiting for review
