Repository CESNET/perun, pull requests merged in 2020-01, with the labels that each got.

#2523 Logging info about missing roles in config
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunRolesLoader.java
Labels: merge soon

#2536 Fixed loading initial data in the Cache and saving the Attribute
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AttributesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/CacheManager.java
Labels: merge soon, waiting for review

#2513 Added new exceptions and their usage to registrar
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/MailManager.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/exceptions/ApplicationMailAlreadyRemovedException.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/exceptions/ApplicationMailExistsException.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/exceptions/ApplicationMailNotExistsException.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/MailManagerImpl.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/JsonErrorHandler.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/model/PerunError.java
Labels: merge soon

#2540 Fixed audit messages resolving in user:virt:userCertDNs
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_userCertDNs.java
Labels: merge soon

#2538 implemented java CLI tool listOfVoMembersWithCertificate
  perun-cli-java/src/main/java/cz/metacentrum/perun/cli/commands/ListOfVoMembersWithCertificate.java
  perun-openapi/openapi.yml
Labels: merge soon

#2500 Use voPersonExternalAffiliation instead of forwardedScopedAffiliation
  perun-base/src/main/java/cz/metacentrum/perun/core/api/CoreConfig.java
  perun-base/src/main/resources/perun-base.xml
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/registrartabs/EditFormItemTabItem.java
Labels: merge soon

#2535 Forbid indirect relationship for group unions
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupsManagerEntryIntegrationTest.java
Labels: waiting for review

#1505 Refresh of all attributes in setRequiredAttributes
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/AttributesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
Labels: manual test needed

#2515 Mail manager refactor
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/MailManagerImpl.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
Labels: merge soon

#2542 make ldapc read-only w.r.t. the Perun db
  perun-core/src/main/java/cz/metacentrum/perun/core/api/AuditMessagesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/AuditMessagesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuditMessagesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/AuditMessagesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AuditMessagesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/AuditMessagesManagerImplApi.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/beans/LdapProperties.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/main/LdapcStarter.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/processor/EventDispatcher.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/processor/impl/EventDispatcherImpl.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/service/LdapcManager.java
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/service/impl/LdapcManagerImpl.java
  perun-ldapc/src/main/resources/perun-ldapc.xml
Labels: merge soon
