Repository CESNET/perun, pull requests merged in 2020-10, with the labels that each got.

#2910 Registrar - name prefills improvement
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
Labels: merge soon

#2915 CORE: Fixed search for standard users
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
Labels: merge soon, waiting for review

#2903 Sponsor existing user
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/MembersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/MembersManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/MembersManagerMethod.java
Labels: waiting for changes, waiting for review

#2916 Added createSponsoredMembers
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/MembersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/DummyPasswordManagerModule.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/MembersManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/MembersManagerMethod.java
Labels: merge soon, waiting for review

#2919 RPC: Fixed returned type in RPC docs
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/MembersManagerMethod.java
Labels: merge soon

#2914 Add method getSponsors to OpenApi
  perun-openapi/openapi.yml
Labels: merge soon

#2921 remove VOADMIN privilege to create resource
  perun-base/src/main/resources/perun-roles.yml
Labels: waiting for review

#2913 New method for getting sponsored members and their sponsors
  perun-base/src/main/java/cz/metacentrum/perun/core/api/MemberWithSponsors.java
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/MembersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/MembersManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/MembersManagerMethod.java
Labels: merge soon

#2869 Configurable role management
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/AuthorizationEvents/RoleSetForGroup.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/AuthorizationEvents/RoleSetForUser.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/AuthorizationEvents/RoleUnsetForGroup.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/AuthorizationEvents/RoleUnsetForUser.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/RoleAlreadySetException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/RoleCannotBeManagedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/RoleNotSetException.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/AuthzResolver.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/FacilitiesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/GroupsManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/ResourcesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/SecurityTeamsManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/VosManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/FacilitiesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ResourcesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/SecurityTeamsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/UsersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/VosManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/GroupsManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/SecurityTeamsManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/VosManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AuthzResolverImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunPoliciesContainer.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunRolesLoader.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/AuthzResolverImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/SecurityTeamsManagerEntryIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/AuthzResolverImplIntegrationTest.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/EduGain.java
  perun-voot/src/test/java/cz/metacentrum/perun/voot/VOOTMainAndFilterIntegrationTest.java
  perun-voot/src/test/java/cz/metacentrum/perun/voot/VOOTSortIntegrationTest.java
Labels: waiting for review

#2928 fix messages in PrivilegeException
  perun-cabinet/src/main/java/cz/metacentrum/perun/cabinet/api/CabinetManager.java
  perun-cabinet/src/main/java/cz/metacentrum/perun/cabinet/api/impl/CabinetManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/AttributesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/GroupsManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ServicesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/UsersManagerEntry.java
Labels: waiting for review

#2924 Searching for users by strings with spaces
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/MembersManagerEntryIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/UsersManagerEntryIntegrationTest.java
Labels: waiting for review

#2925 fix forgotten tasks in WAITING state
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/scheduling/PropagationMaintainer.java
Labels: merge soon

#2912 Script for finding groups inconsistencies
  perun-db/find_group_inconsistencies
Labels: waiting for review

#2932 Script for assigning a service to facility's resources
  perun-cli/assignServiceToResourcesWithSpecificService
Labels: waiting for review

#2927 OpenAPI method added
  perun-openapi/openapi.yml
Labels: waiting for review

#2930 Sponsorship Expiration - cron
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/ExpirationNotifScheduler/SponsorshipExpirationInAMonth.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/ExpirationNotifScheduler/SponsorshipExpirationInDays.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/ExpirationNotifScheduler/SponsorshipExpired.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/EnrichedSponsorship.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/MembersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/MembersManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/MembersManagerEntryIntegrationTest.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/ExpirationNotifScheduler.java
  perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/ExpirationNotifSchedulerTest.java
Labels: waiting for review

#2920 Optional expiration for sponsored members
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_vo_attribute_def_def_membershipExpirationRules.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/modules/attributes/AbstractMembershipExpirationRulesModule.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/MembersManagerEntryIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_vo_attribute_def_def_membershipExpirationRulesTest.java
Labels: waiting for review

#2931 Create new roles GROUPOBSERVER, RESOURCEOBSERVER, and FACILITYOBSERVER
  perun-base/src/main/java/cz/metacentrum/perun/core/api/Role.java
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
  perun-core/src/test/java/cz/metacentrum/perun/core/api/AuthzResolverIntegrationTest.java
Labels: merge soon

#2933 Fix of creating application in VSUP registrar module
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/RegistrarManager.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/Vsup.java
Labels: merge soon

#2937 CORE: Fixed ExtSourceINET regex
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceINET.java
Labels: merge soon

#2939 GetAdminGroups - allow SPONSOR role
  perun-core/src/main/java/cz/metacentrum/perun/core/api/AuthzResolver.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/VosManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/VosManagerEntry.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/VosManagerMethod.java
Labels: waiting for review

#2938 Fixed regexes in ldapc
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/AuthorizationEvents/RoleSetForGroup.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/AuthorizationEvents/RoleSetForUser.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/AuthorizationEvents/RoleUnsetForGroup.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/AuthorizationEvents/RoleUnsetForUser.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/FacilityManagerEvents/AdminAddedForFacility.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/FacilityManagerEvents/AdminGroupAddedForFacility.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/FacilityManagerEvents/AdminGroupRemovedForFacility.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/FacilityManagerEvents/AdminRemovedForFacility.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/GroupManagerEvents/AdminAddedForGroup.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/GroupManagerEvents/AdminGroupAddedForGroup.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/GroupManagerEvents/AdminGroupRemovedFromGroup.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/GroupManagerEvents/AdminRemovedForGroup.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/ResourceManagerEvents/AdminGroupAddedForResource.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/ResourceManagerEvents/AdminGroupRemovedForResource.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/ResourceManagerEvents/AdminUserAddedForResource.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/ResourceManagerEvents/AdminUserRemovedForResource.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/SecurityTeamsManagerEvents/AdminAddedForSecurityTeam.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/SecurityTeamsManagerEvents/AdminGroupAddedForSecurityTeam.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/SecurityTeamsManagerEvents/AdminGroupRemovedFromSecurityTeam.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/SecurityTeamsManagerEvents/AdminRemovedFromSecurityTeam.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/VoManagerEvents/AdminAddedForVo.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/VoManagerEvents/AdminGroupAddedForVo.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/VoManagerEvents/AdminGroupRemovedForVo.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/VoManagerEvents/AdminRemovedForVo.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
  perun-ldapc/src/main/resources/perun-ldapc.xml
Labels: merge soon

#2941 Using function unaccent() on input search string
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/UsersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
Labels: waiting for review

#2945 Specific users refactorization
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/UsersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/UsersManagerEntryIntegrationTest.java
Labels: waiting for review

#2946 Support of method getHashedData (hierarchical and with groups)
  perun-cli/Perun/Common.pm
  perun-cli/Perun/ServicesAgent.pm
  perun-cli/Perun/beans/HashedGenData.pm
Labels: merge soon

#2950 CreateSponsoredMember - email
  perun-core/src/main/java/cz/metacentrum/perun/core/api/MembersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/MembersManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/MembersManagerMethod.java
Labels: waiting for review

#2953 CreateSponsoredMembers - new name format
  perun-core/src/main/java/cz/metacentrum/perun/core/api/MembersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/MembersManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/MembersManagerMethod.java
Labels: waiting for review

#2955 New SPONSORSHIP role
  perun-base/src/main/java/cz/metacentrum/perun/core/api/Role.java
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/MembersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/MembersManagerImplApi.java
Labels: waiting for review

#2957 Fix policies for sponsor methods
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
Labels: waiting for review

#2963 CreateSponsoredMembers - email
  perun-core/src/main/java/cz/metacentrum/perun/core/api/MembersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/MembersManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/MembersManagerMethod.java
Labels: waiting for review

#2948 CLI: Removed non-existing managers
  perun-cli/Perun/Agent.pm
  perun-cli/Perun/ControlPanel.pm
Labels: merge soon

#2949 CORE: Removed attribute modules for deleted services
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_resource_attribute_def_def_openNebulaGroupName.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_openNebulaSSHAdminKeys.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_resource_attribute_def_def_openNebulaGroupNameTest.java
Labels: merge soon

#2959 Exceptions for invalid password reset request
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/PasswordResetLinkExpiredException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/PasswordResetLinkNotValidException.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/UsersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/UsersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/UsersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/UsersManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/UsersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/UsersManagerImplApi.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/UsersManagerMethod.java
Labels: merge soon

#2942 New hash data format
  perun-base/src/main/java/cz/metacentrum/perun/core/api/GenDataNode.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/HashedGenData.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/ServicesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ServicesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/provisioning/GroupsHashedDataGenerator.java
  perun-core/src/main/java/cz/metacentrum/perun/core/provisioning/HierarchicalHashedDataGenerator.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/ServicesManagerEntryIntegrationTest.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ServicesManagerMethod.java
Labels: merge soon
