Repository CESNET/perun, pull requests merged in 2020-06, with the labels that each got.

#2723 eduteams:persistent-shadow was made configurable
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_eduteams_persistent_shadow.java
Labels: waiting for review

#2731 requestPreferredEmailChange method added to OpenAPI
  perun-openapi/openapi.yml
Labels: waiting for review

#2733 Fix bug where two http requests changed shared stateChanging attribute
  perun-base/src/main/java/cz/metacentrum/perun/rpc/deserializer/Deserializer.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/Api.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/ApiCaller.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/AttributesManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/AuditMessagesManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/AuthzResolverMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/CabinetManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ExtSourcesManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/FacilitiesManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/GroupsManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/MembersManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/NotificationManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/OwnersManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/RegistrarManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ResourcesManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/SearcherMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/SecurityTeamsManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ServicesManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/UsersManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/VosManagerMethod.java
Labels: merge soon

#2725 Refactorization of persistent shadow modules
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_bbmri_persistent_shadow.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_bbmri_test_persistent_shadow.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_eduteams_acc_persistent_shadow.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_eduteams_persistent_shadow.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_einfraid_persistent_shadow.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_elixir_persistent_shadow.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_fenix_persistent_shadow.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_lifescienceid_persistent_shadow.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_surf_ram_persistent_shadow.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_westlife_persistent_shadow.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/modules/attributes/UserPersistentShadowAttribute.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/modules/attributes/UserPersistentShadowAttributeWithConfig.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_fenix_persistent_shadowTest.java
Labels: merge soon

#2739 addUserExtSource method definition added to OpenAPI
  perun-openapi/openapi.yml
Labels: waiting for review

#2738 APPS: Implement password strength check for du-samba passwords
  perun-apps/apps/du-samba/index.html
  perun-apps/apps/du-samba/js/AlternativePassword.js
Labels: merge soon

#2734 New module for user virtual attribute sponsoredMembershipInOrganizations
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_sponsoredMembershipInOrganizations.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_sponsoredMembershipInOrganizationsTest.java
Labels: merge soon

#2743 fix uniqueness for multi-valued attributes
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/model/impl/MultipleAttributeValueExtractor.java
Labels: merge soon

#2741 New method for looking for groups by attributes
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/SearcherBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/SearcherBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/SearcherImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/SearcherImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/bl/SearcherBlImplTest.java
Labels: waiting for changes

#2724 New assignServices method
  perun-core/src/main/java/cz/metacentrum/perun/core/api/ResourcesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/AttributesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ResourcesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ResourcesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AttributesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/AttributesManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/bl/AttributesManagerBlImplUnitTests.java
  perun-core/src/test/java/cz/metacentrum/perun/core/bl/ResourcesManagerBlImplUnitTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/AttributesManagerImplIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ResourcesManagerMethod.java
Labels: merge soon

#2748 CORE: Fixed SQL for required attributes for list of services
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AttributesManagerImpl.java
Labels: merge soon

#2740 add new attribute for sponsored membership in organizations
  perun-utils/ldapc-scripts/schemas/perun-schema.ldif
Labels: merge soon

#2676 remove support for multiple engines
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/TasksManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/TasksManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/TasksManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/TasksManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_resource_attribute_def_def_systemUnixGIDTest.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/dao/ProcessingRuleDao.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/dao/RulesDao.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/dao/jdbc/ProcessingRuleDaoJdbc.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/dao/jdbc/RulesDaoJdbc.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/jms/EngineMessageConsumer.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/jms/EngineMessageProcessor.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/jms/EngineMessageProducer.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/jms/EngineMessageProducerFactory.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/jms/EngineMessageProducerPool.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/processing/EventProcessor.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/processing/SmartMatcher.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/processing/impl/SmartMatcherImpl.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/scheduling/SchedulingPool.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/scheduling/TaskScheduler.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/scheduling/impl/SchedulingPoolImpl.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/service/DispatcherManager.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/service/impl/DispatcherManagerImpl.java
  perun-dispatcher/src/main/resources/perun-dispatcher.xml
  perun-dispatcher/src/test/java/cz/metacentrum/perun/dispatcher/unit/EventProcessorTest.java
  perun-dispatcher/src/test/java/cz/metacentrum/perun/dispatcher/unit/SchedulingPoolTest.java
  perun-engine/src/main/java/cz/metacentrum/perun/engine/jms/JMSQueueManager.java
  perun-engine/src/main/java/cz/metacentrum/perun/engine/processing/impl/EventParserImpl.java
  perun-engine/src/test/java/cz/metacentrum/perun/engine/AbstractEngineTest.java
  perun-engine/src/test/java/cz/metacentrum/perun/engine/unit/EventParserImplTest.java
Labels: merge soon

#2747 CORE,RPC,GUI: Handle assign/remove services as a list
  perun-core/src/main/java/cz/metacentrum/perun/core/api/ResourcesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ResourcesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ResourcesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntry.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ResourcesManagerMethod.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/resourcesManager/AssignServices.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/resourcesManager/RemoveServices.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/resourcestabs/AssignServiceTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/resourcestabs/CreateFacilityResourceManageServicesTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/resourcestabs/ResourceAssignedServicesTabItem.java
Labels: merge soon

#2718 OpenApi Cabinet Manager
  perun-openapi/openapi.yml
Labels: waiting for review

#2750 CORE: Optimize implementation of isTrulyRequiredAttribute
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
Labels: merge soon

#2737 CORE,GUI: Login / password checks for einfra
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/InvalidLoginException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/PasswordStrengthException.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/MembersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/UsersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ModulesUtilsBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/UsersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ModulesUtilsBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/UsersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/UsersManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/DummyPasswordManagerModule.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/EinfraPasswordManagerModule.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/GenericPasswordManagerModule.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/MuPasswordManagerModule.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/SambaduPasswordManagerModule.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/modules/pwdmgr/PasswordManagerModule.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_ceitecTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_eduroam_vsupTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_eduteams_acc_nicknameTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_eduteams_nicknameTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_fenix_nicknameTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_vsupTest.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/UsersManagerMethod.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/client/applicationresources/RegistrarFormItemGenerator.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/usersManager/IsLoginAvailable.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/memberstabs/CreateServiceMemberInVoTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/userstabs/AddLoginTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/userstabs/SelfPasswordTabItem.java
Labels: merge soon

#2756 GUI: Respect disabling opt-out for mailing lists
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/userstabs/SelfResourcesSettingsTabItem.java
Labels: merge soon

#2745 OpenApi AuthzResolver
  perun-openapi/openapi.yml
Labels: waiting for review

#2755 Synchronization of group structures by group login (not name)
  perun-base/src/main/java/cz/metacentrum/perun/core/api/CandidateGroup.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/GroupsManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ExtSourcesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceSql.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupStructureSynchronizationIntegrationTest.java
Labels: waiting for review

#2752 Methods definitions related to preferred email change added to OpenAPI
  perun-openapi/openapi.yml
Labels: waiting for changes

#2759 CORE,DB: Dropped Oracle DB definition, migration scripts and changelog
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/DatabaseManagerBlImpl.java
  perun-core/src/main/resources/oracleChangelog.txt
  perun-db/README.md
  perun-db/clearTasksResults
  perun-db/delete_tables.pl
  perun-db/export_oracle_to_oracle.pl
  perun-db/export_oracle_to_postgres.pl
  perun-db/export_postgres_to_postgres.pl
  perun-db/oracle.sql
  perun-db/table_order
  perun-db/table_order_base
  perun-db/tasksResultClear.ora
Labels: merge soon

#2760 Fix wrong behavior for unixGID when adding group to resource
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_resource_attribute_def_virt_unixGID.java
Labels: bug, merge soon

#2757 Optimized assignGroupsToResource
  perun-core/src/main/java/cz/metacentrum/perun/core/api/ResourcesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ResourcesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ResourcesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntryIntegrationTest.java
Labels: merge soon

#2761 Group structure sync - additional attributes
  perun-base/src/main/java/cz/metacentrum/perun/core/api/CandidateGroup.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ExtSourcesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceSql.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupStructureSynchronizationIntegrationTest.java
Labels: waiting for review

#2765 removed artificial limits on varchar lengths
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/resources/hsqldbChangelog.txt
  perun-core/src/main/resources/postgresChangelog.txt
  perun-db/postgres.sql
Labels: merge soon

#2769 Removed unchecked exceptions from throws
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/AttributesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_enitityless_attribute_def_def_namespace_UIDRanges.java
Labels: waiting for review

#2762 openapi
  perun-openapi/openapi.yml
Labels: waiting for review
