Repository CESNET/perun, pull requests merged in 2020-02, with the labels that each got.

#2553 ENGINE: Removed unused cron properties
  perun-engine/src/main/resources/perun-engine.xml
Labels: merge soon

#2551 Add new method for testing database performance
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/java/cz/metacentrum/perun/core/api/DatabaseManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/DatabaseManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/DatabaseManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/DatabaseManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/DatabaseManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/DatabaseManagerImplApi.java
  perun-core/src/main/resources/hsqldbChangelog.txt
  perun-core/src/main/resources/oracleChangelog.txt
  perun-core/src/main/resources/postgresChangelog.txt
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/DatabaseManagerEntryIntegrationTest.java
  perun-db/oracle.sql
  perun-db/postgres.sql
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/DatabaseManagerMethod.java
Labels: waiting for review

#2550 Custom logging in ConsolidatorManager
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/ConsolidatorManagerImpl.java
Labels: merge soon

#2559 Change exception thrown when name was wrongly parsed from raw text
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ParseUserNameException.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/MembersManagerEntryIntegrationTest.java
Labels: merge soon

#2562 REGISTRAR: Support login generating workflow
  perun-base/src/main/java/cz/metacentrum/perun/registrar/model/ApplicationFormItemWithPrefilledValue.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/RegistrarModule.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/BBMRICollections.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/BBMRINetworks.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/Ceitec.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/CeitecNcbr.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/DefaultRegistrarModule.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/Du.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/DuSoft.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/ELIXIRCILogonDNGenerator.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/EduGain.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/EduTEAMS.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/Eduroam.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/Elixir.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/ElixirBonaFideStatus.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/Elixircz.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/LifescienceHostel.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/Metacentrum.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/Sitola.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/Vsup.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/WeNMR.java
Labels: merge soon

#2568 Remove unused attribute modules and their tests
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_resource_attribute_def_def_dataLimit.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_resource_attribute_def_def_dataQuota.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_resource_attribute_def_def_filesLimit.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_resource_attribute_def_def_filesQuota.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_resource_attribute_def_def_defaultDataLimit.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_resource_attribute_def_def_defaultDataQuota.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_resource_attribute_def_def_defaultFilesLimit.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_resource_attribute_def_def_defaultFilesQuota.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_resource_attribute_def_def_dataLimitTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_resource_attribute_def_def_dataQuotaTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_resource_attribute_def_def_filesLimitTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_resource_attribute_def_def_filesQuotaTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_resource_attribute_def_def_defaultDataLimitTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_resource_attribute_def_def_defaultDataQuotaTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_resource_attribute_def_def_defaultFilesLimitTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_resource_attribute_def_def_defaultFilesQuotaTest.java
Labels: merge soon

#2578 Added support for user virt attributes eIDASPersonIdentifiers and europeanStudentIDs
  perun-base/src/main/java/cz/metacentrum/perun/core/api/CoreConfig.java
  perun-base/src/main/resources/perun-base.xml
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_eIDASPersonIdentifiers.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_europeanStudentIDs.java
  perun-ldapc/src/main/resources/perun-ldapc.xml
  perun-utils/ldapc-scripts/schemas/perun-schema.ldif
Labels: merge soon

#2574 Add member-group attributes for object RichGroup
  perun-core/src/main/java/cz/metacentrum/perun/core/api/GroupsManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/GroupsManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/GroupsManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AttributesManagerImpl.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupsManagerEntryIntegrationTest.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/GroupsManagerMethod.java
Labels: merge soon

#2584 Removed unused service_principal table
  perun-base/src/test/resources/test-data.sql
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AuthzResolverImpl.java
  perun-core/src/main/resources/hsqldbChangelog.txt
  perun-core/src/main/resources/oracleChangelog.txt
  perun-core/src/main/resources/postgresChangelog.txt
  perun-db/oracle.sql
  perun-db/postgres.sql
  perun-db/table_order
Labels: merge soon

#2564 OpenApi - RegistrarManager Methods
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/RegistrarManagerMethod.java
Labels: waiting for changes
