Repository CESNET/perun, pull requests merged in 2021-06, with the labels that each got.

#3236 refactor(synchronizations): clean updateMemberStatus method
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
Labels: waiting for review

#3235 feat(openapi): add openapi description of new group-resource assignment methods
  perun-openapi/openapi.yml
Labels: waiting for review

#3237 fix(synchronizations): don't validate expired members
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
Labels: multiple reviews needed, waiting for review

#3238 New column status in groups_resources
  perun-base/src/main/java/cz/metacentrum/perun/core/api/GroupResourceStatus.java
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/FacilitiesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/GroupsManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/MembersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ResourcesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/UsersManagerImpl.java
  perun-core/src/main/resources/postgresChangelog.txt
  perun-db/postgres.sql
Labels: waiting for review

#3242 Password-related methods
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/UsersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/UsersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/UsersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/UsersManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/GenericPasswordManagerModule.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/modules/pwdmgr/PasswordManagerModule.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/UsersManagerMethod.java
Labels: waiting for review

#3241 Disabled and hidden icons added also to old GUI
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/client/resources/SmallIcons.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/registrarManager/GetFormItems.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/registrartabs/PreviewFormTabItem.java
Labels: waiting for review

#3243 GUI: show person preffered email on embedded application
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/registrarManager/GetApplicationDataById.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/registrartabs/ApplicationDetailTabItem.java
Labels: waiting for review

#3244 Core - new methods to list group-resource assignments
  perun-base/src/main/java/cz/metacentrum/perun/core/api/AssignedGroup.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/AssignedResource.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/EnrichedGroup.java
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/ResourcesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/GroupsManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ResourcesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ResourcesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/GroupsManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ResourcesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/ResourcesManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntryIntegrationTest.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ResourcesManagerMethod.java
Labels: waiting for review

#3240 Merging attributes in structure synchronization
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/AttributesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupAndGroupStructureSynchronizationIntegrationTest.java
Labels: waiting for review

#3247 Example objects for resource-group
  perun-utils/rpc-methods-javadoc-generator/parseRpcMethods.pl
Labels: waiting for review

#3245 Password manager for mu-adm namespace
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/MuadmPasswordManagerModule.java
Labels: waiting for review

#3251 Bumped development version to 3.27.0-SNAPSHOT
  perun-auditlogger/pom.xml
  perun-auditparser/pom.xml
  perun-base/pom.xml
  perun-cabinet/pom.xml
  perun-cli-java/pom.xml
  perun-cli/Perun/Agent.pm
  perun-core/pom.xml
  perun-dispatcher/pom.xml
  perun-engine/pom.xml
  perun-ldapc/pom.xml
  perun-notification/pom.xml
  perun-openapi/openapi.yml
  perun-openapi/pom.xml
  perun-registrar-lib/pom.xml
  perun-rpc/pom.xml
  perun-scim/pom.xml
  perun-voot/pom.xml
  perun-web-gui/pom.xml
  pom.xml
Labels: waiting for review

#3252 fix(openapi): Remove invalid parameter from method
  perun-openapi/openapi.yml
Labels: waiting for review

#3254 Facility in AssignedResource class
  perun-base/src/main/java/cz/metacentrum/perun/core/api/AssignedResource.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ResourcesManagerImpl.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
Labels: waiting for review

#3256 Removing perun-voot and ExtSourceVOOT
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceVOOT.java
  perun-core/src/main/resources/perun-core.xml
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/ExtSourceVOOTTest.java
  perun-rpc/pom.xml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/Api.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/ApiCaller.java
  perun-utils/rpc-methods-javadoc-generator/parseRpcMethods.pl
  perun-voot/pom.xml
  perun-voot/src/main/java/cz/metacentrum/perun/voot/Email.java
  perun-voot/src/main/java/cz/metacentrum/perun/voot/Response.java
  perun-voot/src/main/java/cz/metacentrum/perun/voot/VOOT.java
  perun-voot/src/main/java/cz/metacentrum/perun/voot/VOOTException.java
  perun-voot/src/main/java/cz/metacentrum/perun/voot/VOOTGroup.java
  perun-voot/src/main/java/cz/metacentrum/perun/voot/VOOTMember.java
  perun-voot/src/main/java/cz/metacentrum/perun/voot/VOOTPerson.java
  perun-voot/src/main/java/cz/metacentrum/perun/voot/comparators/vootgroupcomparator/VOOTGroupDefaultDescComparator.java
  perun-voot/src/main/java/cz/metacentrum/perun/voot/comparators/vootgroupcomparator/VOOTGroupDescriptionAscComparator.java
  perun-voot/src/main/java/cz/metacentrum/perun/voot/comparators/vootgroupcomparator/VOOTGroupDescriptionDescComparator.java
  perun-voot/src/main/java/cz/metacentrum/perun/voot/comparators/vootgroupcomparator/VOOTGroupIdAscComparator.java
  perun-voot/src/main/java/cz/metacentrum/perun/voot/comparators/vootgroupcomparator/VOOTGroupIdDescComparator.java
  perun-voot/src/main/java/cz/metacentrum/perun/voot/comparators/vootgroupcomparator/VOOTGroupMembershipRoleAscComparator.java
  perun-voot/src/main/java/cz/metacentrum/perun/voot/comparators/vootgroupcomparator/VOOTGroupMembershipRoleDescComparator.java
  perun-voot/src/main/java/cz/metacentrum/perun/voot/comparators/vootgroupcomparator/VOOTGroupTitleAscComparator.java
  perun-voot/src/main/java/cz/metacentrum/perun/voot/comparators/vootgroupcomparator/VOOTGroupTitleDescComparator.java
  perun-voot/src/main/java/cz/metacentrum/perun/voot/comparators/vootmembercomparator/VOOTMemberDefaultDescComparator.java
  perun-voot/src/main/java/cz/metacentrum/perun/voot/comparators/vootmembercomparator/VOOTMemberDisplayNameAscComparator.java
  perun-voot/src/main/java/cz/metacentrum/perun/voot/comparators/vootmembercomparator/VOOTMemberDisplayNameDescComparator.java
  perun-voot/src/main/java/cz/metacentrum/perun/voot/comparators/vootmembercomparator/VOOTMemberIdAscComparator.java
  perun-voot/src/main/java/cz/metacentrum/perun/voot/comparators/vootmembercomparator/VOOTMemberIdDescComparator.java
  perun-voot/src/main/java/cz/metacentrum/perun/voot/comparators/vootmembercomparator/VOOTMemberMembershipRoleAscComparator.java
  perun-voot/src/main/java/cz/metacentrum/perun/voot/comparators/vootmembercomparator/VOOTMemberMembershipRoleDescComparator.java
  perun-voot/src/main/resources/perun-voot.xml
  perun-voot/src/test/java/cz/metacentrum/perun/voot/AbstractVOOTTest.java
  perun-voot/src/test/java/cz/metacentrum/perun/voot/VOOTLimitResultIntegrationTest.java
  perun-voot/src/test/java/cz/metacentrum/perun/voot/VOOTMainAndFilterIntegrationTest.java
  perun-voot/src/test/java/cz/metacentrum/perun/voot/VOOTSortIntegrationTest.java
  perun-voot/src/test/java/cz/metacentrum/perun/voot/VOOTSubGroupsIntegrationTest.java
  pom.xml
Labels: waiting for review

#3248 Core - new methods for activating group-resource assignments
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/GroupResourceStatusException.java
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/ResourcesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ResourcesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ResourcesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ResourcesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/ResourcesManagerImplApi.java
  perun-core/src/main/resources/perun-core.xml
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ResourcesManagerMethod.java
Labels: waiting for review

#3253 Removing facility contact logic
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/FacilityManagerEvents/GroupContactsRemovedForFacility.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/FacilityManagerEvents/GroupsAddedToContactGroupOfFacility.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/FacilityManagerEvents/GroupsRemovedFromContactGroupOfFacility.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/FacilityManagerEvents/OwnerContactsRemovedForFacility.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/FacilityManagerEvents/OwnersAddedToContactGroupOfFacility.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/FacilityManagerEvents/OwnersRemovedFromContactGroupOfFacility.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/FacilityManagerEvents/UserContactsRemovedForFacility.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/FacilityManagerEvents/UsersAddedToContactGroupOfFacility.java
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/FacilityManagerEvents/UsersRemovedFromContactGroupOfFacility.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/ContactGroup.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/FacilityContactExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/FacilityContactNotExistsException.java
  perun-base/src/main/resources/perun-roles.yml
  perun-base/src/test/resources/test-schema.sql
  perun-cli/Perun/Common.pm
  perun-cli/Perun/FacilitiesAgent.pm
  perun-cli/Perun/beans/ContactGroup.pm
  perun-cli/addFacilityContacts
  perun-cli/getContactsAssignedToGroup
  perun-cli/getContactsAssignedToOwner
  perun-cli/getContactsAssignedToUser
  perun-cli/getContactsOfFacility
  perun-cli/listOfAllFacilitiesGroupContacts
  perun-cli/removeFacilityContacts
  perun-core/src/main/java/cz/metacentrum/perun/core/api/FacilitiesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/FacilitiesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/FacilitiesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/OwnersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/UsersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/FacilitiesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/FacilitiesManagerImplApi.java
  perun-core/src/main/resources/perun-core.xml
  perun-core/src/main/resources/postgresChangelog.txt
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntryIntegrationTest.java
  perun-db/postgres.sql
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/FacilitiesManagerMethod.java
Labels: waiting for review

#3257 Mu-adm password strenght
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/MuadmPasswordManagerModule.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/MuadmPasswordManagerModuleTest.java
Labels: waiting for changes

#3266 added method to rpc for getting member in group context
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/GroupsManagerMethod.java
Labels: waiting for review

#3268 CLI: Fixed changePassword() method param name
  perun-cli/changePassword
  perun-cli/resetPassword
Labels: merge soon

#3272 fix(registrar): Fix embedded groups item without CS locale
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
Labels: bug, waiting for review

#3271 Method returning RichMembers from group by memberIds
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/GroupsManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/GroupsManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupsManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/GroupsManagerMethod.java
Labels: waiting for review

#3273 Added property uuid to openapi
  perun-openapi/openapi.yml
Labels: waiting for review

#3274 Searching users and members by user UUID
  perun-core/src/main/java/cz/metacentrum/perun/core/api/UsersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/UsersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/MembersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/UsersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/MembersManagerImplApi.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/UsersManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/MembersManagerEntryIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/UsersManagerEntryIntegrationTest.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/MembersManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/UsersManagerMethod.java
Labels: merge soon

#3277 perf(core): Optimize member search sql
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/MembersManagerImpl.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/MembersManagerEntryIntegrationTest.java
Labels: waiting for review
