Repository CESNET/perun, pull requests merged in 2021-07, with the labels that each got.

#3281 perf(core): Optimize user and member search SQL
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/MembersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/UsersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
Labels: waiting for review

#3280 fix(core): Fix module class name
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_group_attribute_def_virt_o365SendOnBehalf.java
Labels: waiting for review

#3279 refactor: removed deprecated preferred mail change methods
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/UsersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/UsersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/UsersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/UsersManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/UsersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/UsersManagerImplApi.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/UsersManagerMethod.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/client/WebGui.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/usersManager/ValidatePreferredEmailChange.java
Labels: merge soon

#3282 feat: adGroupname attribute now allows '-' symbol
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_adGroupName.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_adGroupNameTest.java
Labels: waiting for review

#3288 feat(core): adjustment for generated passwords for Einfra and MU
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/EinfraPasswordManagerModule.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/MuPasswordManagerModule.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/EinfraPasswordManagerModuleTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/MuPasswordManagerModuleTest.java
Labels: waiting for review

#3285 feat(core): Add ResourceAssignmentActivator component
  perun-base/src/main/java/cz/metacentrum/perun/core/api/GroupResourceAssignment.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ResourcesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ResourcesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ResourceAssignmentActivator.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ResourcesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/ResourcesManagerImplApi.java
  perun-core/src/main/resources/perun-core.xml
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntryIntegrationTest.java
Labels: waiting for changes

#3290 fix(core): Audit group-resource deactivation
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ResourcesManagerBlImpl.java
Labels: waiting for review

#3291 feat(core): add async mode for assignGroupToResource method
  perun-core/src/main/java/cz/metacentrum/perun/core/api/ResourcesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ResourcesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ResourcesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/bl/FacilitiesManagerBlImplTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/bl/ResourcesManagerBlImplTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/bl/UsersManagerBlImplTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/AttributesManagerEntryIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntryIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupsManagerEntryIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/MembersManagerEntryIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/ModulesUtilsEntryIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntryIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/SearcherEntryIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/ServicesManagerEntryIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/UsersManagerEntryIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/AttributesManagerImplIntegrationTest.java
  perun-dispatcher/src/test/java/cz/metacentrum/perun/dispatcher/unit/EventProcessorTest.java
  perun-dispatcher/src/test/java/cz/metacentrum/perun/dispatcher/unit/EventServiceResolverTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ResourcesManagerMethod.java
Labels: waiting for review

#3293 feat(registrar): prefill group application with vo app values
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/RegistrarManager.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
Labels: waiting for review

#3299 feat(perun): method isLoginAvailable added to OpenAPI
  perun-openapi/openapi.yml
Labels: waiting for review

#3300 chore(maven): bumped development version to 3.29.0-SNAPSHOT
  perun-auditlogger/pom.xml
  perun-auditparser/pom.xml
  perun-base/pom.xml
  perun-cabinet/pom.xml
  perun-cli-java/pom.xml
  perun-cli/Perun/Agent.pm
  perun-core/pom.xml
  perun-dispatcher/pom.xml
  perun-engine/pom.xml
  perun-ldapc/pom.xml
  perun-notification/pom.xml
  perun-openapi/openapi.yml
  perun-openapi/pom.xml
  perun-registrar-lib/pom.xml
  perun-rpc/pom.xml
  perun-scim/pom.xml
  perun-web-gui/pom.xml
  pom.xml
Labels: waiting for review

#3298 fix(core): allowed included groups in modules sendAs, sendOnBehalf
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ModulesUtilsBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ModulesUtilsBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_o365SendAsGroups.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_o365SendOnBehalfGroups.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/ModulesUtilsEntryIntegrationTest.java
Labels: waiting for review
