Repository CESNET/perun, pull requests merged in 2021-08, with the labels that each got.

#3304 feat(ldap): Add attribute studentIdentifiers to LDAP schema
  perun-utils/ldapc-scripts/schemas/perun-schema.ldif
Labels: waiting for review

#3302 feat(core): store cause of group-resource assignment failure
  perun-base/src/main/java/cz/metacentrum/perun/core/api/AssignedGroup.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/AssignedResource.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/GroupResourceAssignment.java
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ResourcesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/GroupsManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ResourcesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/ResourcesManagerImplApi.java
  perun-core/src/main/resources/postgresChangelog.txt
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntryIntegrationTest.java
  perun-db/postgres.sql
  perun-openapi/openapi.yml
  perun-utils/rpc-methods-javadoc-generator/parseRpcMethods.pl
Labels: waiting for review

#3307 feat(openapi): add method reserveRandomPassword to OpenAPI
  perun-openapi/openapi.yml
Labels: waiting for review

#3306 ci(githubci): add semantic releasing
  .github/workflows/release.yml
  .github/workflows/semantic-release.yml
  .gitignore
  .releaserc.json
  package-lock.json
  package.json
  perun-auditlogger/pom.xml
  perun-auditparser/pom.xml
  perun-base/pom.xml
  perun-cabinet/pom.xml
  perun-cli-java/pom.xml
  perun-core/pom.xml
  perun-dispatcher/pom.xml
  perun-engine/pom.xml
  perun-ldapc/pom.xml
  perun-notification/pom.xml
  perun-openapi/openapi.yml
  perun-openapi/pom.xml
  perun-registrar-lib/pom.xml
  perun-rpc/pom.xml
  perun-scim/pom.xml
  perun-web-gui/pom.xml
  pom.xml
  update-versions.sh
Labels: waiting for review

#3309 ci(githubci): allow commenting of PRs of commits which were released
  .releaserc.json
Labels: waiting for review

#3303 fix(registrar): Constant-time MAC comparison
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
Labels: waiting for review

#3305 feat(core): allow empty login in module login-namespace:mu-adm
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_mu_adm.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_mu_admTest.java
Labels: waiting for review

#3311 perf(core): adjust threads pool for async tasks
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/resources/perun-core.xml
Labels: waiting for review

#3308 feat(core): new user virtual attribute studentIdentifiers
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_studentIdentifiers.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_studentIdentifiersTest.java
Labels: waiting for review

#3301 feat(registrar): VO and group application notifications adjustment
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/MailManagerImpl.java
Labels: waiting for review

#3314 fix(gui): Fixed unresponsive tabs for form item editing
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/registrarManager/GetFormItems.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/groupstabs/GroupApplicationFormSettingsTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/registrartabs/CreateFormItemTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/registrartabs/EditFormItemTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/vostabs/VoApplicationFormSettingsTabItem.java
Labels: waiting for review

#3315 feat(core): module studentIdentifiers changed to create and remove userExtSources with attributes
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_studentIdentifiers.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_studentIdentifiersTest.java
  perun-utils/ldapc-scripts/schemas/perun-schema.ldif
Labels: waiting for review

#3313 ci(githubci): update CLI version on release
  perun-cli/Perun/Agent.pm
  update-versions.sh
Labels: waiting for review

#3316 fix(core): fixed audit logging for group-resource assignement without services on resource
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ResourcesManagerBlImpl.java
Labels: merge soon

#3310 feat(core): New table groups_resources_state
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ResourcesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/FacilitiesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/GroupsManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/MembersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ResourcesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/UsersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/ResourcesManagerImplApi.java
  perun-core/src/main/resources/postgresChangelog.txt
  perun-db/postgres.sql
Labels: waiting for changes

#3319 make getRichGroupByIdWithAttributesByNames parameter attrNames optional
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/GroupsManagerMethod.java
Labels: waiting for review

#3317 feat: add anonymizeUser method to openApi and CLI
  perun-cli/Perun/UsersAgent.pm
  perun-cli/anonymizeUser
  perun-openapi/openapi.yml
Labels: waiting for review

#3321 fix(registrar): Fixed order of checks since GUI resolves them with priority
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
Labels: waiting for review

#3320 fix(openapi): added missing parameter and methods to openapi
  perun-openapi/openapi.yml
Labels: waiting for review

#3324 feat(registrar): added option to disable finding similar users during registrations
  perun-base/src/main/java/cz/metacentrum/perun/core/api/CoreConfig.java
  perun-base/src/main/resources/perun-base.xml
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
Labels: waiting for review

#3326 fix(registrar): Fix retrieving VO application while initializing registrar
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/RegistrarManager.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
Labels: waiting for review

#3286 fix(core): Unnecessary audit messages
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/GroupsManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/GroupsManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/GroupsManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupsManagerEntryIntegrationTest.java
Labels: waiting for review

#3327 fix(registrar): fixed sending notifications about group application creation to admins
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/RegistrarManager.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
Labels: waiting for review

#3329 fix(core): correctly close connection to extSources
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ExtSourcesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/VosManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ExtSourcesManagerEntry.java
Labels: waiting for review

#3330 fix(core): skip running ResourceAssignmentActivator component in read-only mode
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ResourceAssignmentActivator.java
Labels: waiting for review
