Repository CESNET/perun, pull requests merged in 2021-04, with the labels that each got.

#3134 Registrar - visibility and disabled fields
  perun-base/src/main/java/cz/metacentrum/perun/registrar/model/ApplicationFormItem.java
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/resources/postgresChangelog.txt
  perun-db/postgres.sql
  perun-openapi/openapi.yml
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
  perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/RegistrarBaseIntegrationTest.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/client/applicationresources/RegistrarFormItemGenerator.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/registrarManager/GetApplicationDataById.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/registrarManager/GetFormItems.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/registrarManager/UpdateFormItems.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/model/ApplicationFormItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/registrartabs/CreateFormItemTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/registrartabs/EditFormItemTabItem.java
Labels: waiting for review

#3153 Core - namespace configuration csvGenHeaderDescription
  perun-base/src/main/java/cz/metacentrum/perun/core/api/NamespaceRules.java
  perun-base/src/test/resources/sponsored-accounts-config.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/SponsoredAccountsConfigLoader.java
  perun-openapi/openapi.yml
Labels: waiting for review

#3155 Core - don't allow it4i logins in Einfra
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/EinfraPasswordManagerModule.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/EinfraPasswordManagerModuleTest.java
Labels: waiting for review

#3154 Added filter for members by list of group statuses
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/MembersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/MembersManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/MembersManagerMethod.java
Labels: waiting for review

#3156 Added redirectURL to validation mail
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/MailManagerImpl.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
Labels: waiting for changes

#3159 Show unsaved form items in application form dependency options
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
  perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/RegistrarBaseIntegrationTest.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/client/applicationresources/RegistrarFormItemGenerator.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/registrarManager/GetFormItems.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/groupstabs/GroupApplicationFormSettingsTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/registrartabs/CreateFormItemTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/vostabs/VoApplicationFormSettingsTabItem.java
Labels: merge soon, waiting for changes

#3151 Force delete methods added to OpenAPI
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/GroupsManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/OwnersManagerMethod.java
Labels: waiting for changes

#3163 GUI - alert to new GUI
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/client/WebGui.java
  perun-web-gui/src/main/webapp/PerunWeb.css
Labels: waiting for review

#3164 Modules for adGroupName
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_adGroupName.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_virt_adGroupName.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_adGroupNameTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_virt_adGroupNameTest.java
Labels: waiting for review

#3174 Erasmus username modules
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_erasmus_username.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_login_namespace_erasmus_username.java
Labels: waiting for review

#3178 New application type - EMBEDDED
  perun-base/src/main/java/cz/metacentrum/perun/registrar/model/Application.java
  perun-base/src/main/java/cz/metacentrum/perun/registrar/model/ApplicationForm.java
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/resources/postgresChangelog.txt
  perun-db/postgres.sql
  perun-openapi/openapi.yml
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/RegistrarManager.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/Elixircz.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/RegistrarManagerMethod.java
Labels: waiting for review

#3176 Registrar - prefill group check box
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
  perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/RegistrarBaseIntegrationTest.java
Labels: waiting for review

#3181 Submit embedded groups applications automatically
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/EmbeddedGroupApplicationSubmissionError.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/GroupNotEmbeddedException.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
  perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/RegistrarBaseIntegrationTest.java
Labels: waiting for review

#3184 Core - fixed if condition
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
  perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/RegistrarBaseIntegrationTest.java
Labels: waiting for review

#3171 GUI - groups for auto registration
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/client/localization/ButtonTranslation.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/groupsManager/AddAutoRegGroups.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/groupsManager/GetAutoRegistrationGroups.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/groupsManager/RemoveGroupsFromAutoRegistration.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/RegistrarTabs.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/registrartabs/AddAutoRegGroupTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/registrartabs/AutoRegistrationGroupsTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/vostabs/VoApplicationFormSettingsTabItem.java
Labels: waiting for review

#3187 OLD GUI - recognizing new application item type
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/client/applicationresources/RegistrarFormItemGenerator.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/registrartabs/CreateFormItemTabItem.java
Labels: waiting for review

#3188 OLD GUI - recognizing new application type
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/client/localization/ObjectTranslation.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/client/resources/SmallIcons.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/model/Application.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/widgets/cells/PerunAppTypeCell.java
Labels: waiting for review

#3173 Group member path reconstruction method
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/GroupsManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/GroupsManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/GroupsManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupsManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/GroupsManagerMethod.java
Labels: waiting for review

#3143 Add new registrar modules - LSHostelRI and LSHostelRIAcc
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/LifeScienceHostelRI.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/LifeScienceHostelRIAcc.java
Labels: merge soon, waiting for changes

#3192 Registrar - use initial templates for embedded app
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/MailManagerImpl.java
Labels: waiting for review
