Repository CESNET/perun, pull requests merged in 2021-02, with the labels that each got.

#3067 Remove support for HSQL database
  perun-base/pom.xml
  perun-base/src/main/resources/perun-base.xml
  perun-base/src/test/resources/jdbc.properties
  perun-base/src/test/resources/logback-test.xml
  perun-base/src/test/resources/test-data.sql
  perun-base/src/test/resources/test-schema.sql
  perun-core/pom.xml
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/DatabaseManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Compatibility.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/UsersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
  perun-core/src/main/resources/hsqldbChangelog.txt
  perun-core/src/main/resources/perun-core.xml
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupsManagerEntryIntegrationTest.java
  perun-db/postgres.sql
  perun-dispatcher/src/test/java/cz/metacentrum/perun/dispatcher/AbstractDispatcherTest.java
  perun-dispatcher/src/test/java/cz/metacentrum/perun/dispatcher/unit/EventProcessorTest.java
  perun-dispatcher/src/test/java/cz/metacentrum/perun/dispatcher/unit/EventServiceResolverTest.java
  perun-dispatcher/src/test/java/cz/metacentrum/perun/dispatcher/unit/TaskSchedulerTest.java
  perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/AppAutoRejectionSchedulerTest.java
  pom.xml
Labels: merge soon

#3072 umbrellaIDIdentifier fix
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_umbrellaid_persistent_shadow.java
Labels: merge soon

#3077 CORE: Removed unused config for perunLdapInitializer
  perun-base/src/main/resources/perun-base.xml
Labels: merge soon

#3080 Add scope for the umbrella identifier
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_umbrellaid_persistent_shadow.java
Labels: merge soon

#3082 Added two attributes which allow to block manual member adding
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
Labels: merge soon

#3083 New method getEnrichedFacilities
  perun-base/src/main/java/cz/metacentrum/perun/core/api/EnrichedFacility.java
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/FacilitiesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/FacilitiesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/FacilitiesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntryIntegrationTest.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/FacilitiesManagerMethod.java
Labels: waiting for review

#3087 EnrichedFacility changed to contain owners
  perun-base/src/main/java/cz/metacentrum/perun/core/api/EnrichedFacility.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/FacilitiesManagerBlImpl.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
Labels: waiting for review

#3084 Researcher Access attribute modules
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_login_namespace_researcher_access_persistent_shadow.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_login_namespace_researcher_access_persistent.java
Labels: waiting for review

#3088 Require stronger passwords for MU namespace
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/EinfraPasswordManagerModule.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/MuPasswordManagerModule.java
Labels: merge soon

#3091 CLI: Removed unused HostsAgent
  perun-cli/Perun/Agent.pm
  perun-cli/Perun/FacilitiesAgent.pm
  perun-cli/Perun/HostsAgent.pm
  perun-cli/deleteHost
  perun-cli/removeAllHostAttributes
  perun-cli/removeHostAttribute
  perun-cli/removeHostsAndDestFromFacility
  perun-cli/removeHostsFromAllFacilities
  perun-cli/removeHostsFromFacility
Labels: merge soon

#3051 AutoRejection - custom reject messages
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_applicationAutoRejectMessages.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_vo_attribute_def_def_applicationAutoRejectMessages.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/modules/attributes/AbstractApplicationAutoRejectMessagesModule.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_applicationAutoRejectMessagesTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_vo_attribute_def_def_applicationAutoRejectMessagesTest.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/AppAutoRejectionScheduler.java
  perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/AppAutoRejectionSchedulerTest.java
Labels: waiting for review

#3096 Added check to Destination and Host creation
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/InvalidDestinationException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/InvalidHostnameException.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/FacilitiesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/ServicesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/FacilitiesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ServicesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/FacilitiesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ServicesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ServicesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/FacilitiesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ServicesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/FacilitiesManagerImplApi.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/ServicesManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/AttributesManagerEntryIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntryIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/ServicesManagerEntryIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/ServicesManagerImplIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/UtilsIntegrationTest.java
  perun-engine/src/test/java/cz/metacentrum/perun/engine/AbstractEngineTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/FacilitiesManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ServicesManagerMethod.java
Labels: merge soon

#3093 New method moveMembership
  perun-base/src/main/resources/perun-roles.yml
  perun-cli/Perun/MembersAgent.pm
  perun-cli/moveMembership
  perun-core/src/main/java/cz/metacentrum/perun/core/api/MembersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/MembersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/MembersManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/MembersManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/MembersManagerMethod.java
Labels: waiting for review

#3097 CLI: Added tool to get application by ID
  perun-cli/Perun/Common.pm
  perun-cli/Perun/RegistrarAgent.pm
  perun-cli/Perun/beans/Application.pm
  perun-cli/Perun/beans/ApplicationForm.pm
  perun-cli/getApplicationById
Labels: merge soon

#3090 TasksManager cleanup.
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/TasksManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/TasksManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/FacilitiesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ServicesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/TasksManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/TasksManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/TasksManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/TasksManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/bl/ServicesManagerBlImplTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/bl/TasksManagerBlImplTest.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/scheduling/PropagationMaintainer.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/scheduling/TaskScheduler.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/scheduling/impl/SchedulingPoolImpl.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/service/impl/DispatcherManagerImpl.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/TasksManagerMethod.java
Labels: don't merge, waiting for review

#3101 Core - generate password for sponsored user
  perun-core/src/main/java/cz/metacentrum/perun/core/api/MembersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/MembersManagerMethod.java
Labels: merge soon

#3086 Configuration support for sponsorship
  perun-base/src/main/java/cz/metacentrum/perun/core/api/NamespaceRules.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/NamespaceRulesNotExistsException.java
  perun-base/src/test/resources/sponsored-accounts-config.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/MembersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/MembersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/SponsoredAccountsConfigContainer.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/SponsoredAccountsConfigLoader.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/MembersManagerImplApi.java
  perun-core/src/main/resources/perun-core.xml
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/MembersManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/MembersManagerMethod.java
Labels: waiting for review

#3104 Created method for easier deletion of service from facility
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/FacilitiesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/FacilitiesManagerMethod.java
Labels: waiting for review
