Repository CESNET/perun, pull requests merged in 2021-05, with the labels that each got.

#3196 Bumped development version to 3.24.0-SNAPSHOT
  perun-auditlogger/pom.xml
  perun-auditparser/pom.xml
  perun-base/pom.xml
  perun-cabinet/pom.xml
  perun-cli-java/pom.xml
  perun-cli/Perun/Agent.pm
  perun-core/pom.xml
  perun-dispatcher/pom.xml
  perun-engine/pom.xml
  perun-ldapc/pom.xml
  perun-notification/pom.xml
  perun-openapi/openapi.yml
  perun-openapi/pom.xml
  perun-registrar-lib/pom.xml
  perun-rpc/pom.xml
  perun-scim/pom.xml
  perun-voot/pom.xml
  perun-web-gui/pom.xml
  pom.xml
Labels: waiting for review

#3194 Core - perun apps config
  perun-base/src/test/resources/perun-apps-config.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunAppsConfig.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunAppsConfigLoader.java
  perun-core/src/main/resources/perun-core.xml
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/PerunAppsConfigLoaderTest.java
Labels: waiting for review

#3200 REGISTRAR: Encode URL param for {redirectUrl} notification tag
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/MailManagerImpl.java
Labels: merge soon, waiting for review

#3199 Solve conflict for init and embed group applications
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
  perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/RegistrarBaseIntegrationTest.java
Labels: waiting for review

#3201 Core - bugfix identities alerts
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
Labels: waiting for review

#3193 Check number of embedded groups form items
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/MultipleApplicationFormItemsException.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/RegistrarManager.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
  perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/RegistrarBaseIntegrationTest.java
Labels: waiting for review

#3212 OpenAPI fix in method deleteAuthorship
  perun-openapi/openapi.yml
Labels: waiting for review

#3204 Removed old logic for change password
  perun-core/src/main/java/cz/metacentrum/perun/core/api/UsersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/UsersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/UsersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/UsersManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/UsersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/UsersManagerImplApi.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/UsersManagerMethod.java
Labels: waiting for review

#3214 Embedded app type added to openapi
  perun-openapi/openapi.yml
Labels: waiting for review

#3215 refactor(gui): Send gui domain when requesting email change
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/usersManager/RequestPreferredEmailChange.java
Labels: waiting for review

#3216 Email change using UUID as token
  perun-base/src/main/resources/perun-roles.yml
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/java/cz/metacentrum/perun/core/api/UsersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/UsersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/UsersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/UsersManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/UsersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/UsersManagerImplApi.java
  perun-core/src/main/resources/postgresChangelog.txt
  perun-db/postgres.sql
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/UsersManagerMethod.java
Labels: waiting for review

#3217 Create group form when added to VO's embedded groups
  perun-core/src/main/java/cz/metacentrum/perun/core/api/GroupsManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/GroupsManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/GroupsManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupsManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/RegistrarManager.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
  perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/RegistrarBaseIntegrationTest.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/GroupsManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/RegistrarManagerMethod.java
Labels: waiting for changes

#3226 Preferred mail change using token
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/client/WebGui.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/usersManager/ValidatePreferredEmailChange.java
Labels: waiting for review

#3222 Check linkPath passed to preferred mail change method
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/UsersManagerMethod.java
Labels: waiting for changes

#3232 Fixed subgroup statuses in group members page
  perun-base/src/main/java/cz/metacentrum/perun/core/api/MembersPageQuery.java
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/MembersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/MembersManagerImpl.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/MembersManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/MembersManagerMethod.java
  perun-utils/rpc-methods-javadoc-generator/parseRpcMethods.pl
Labels: waiting for review

#3219 fix(core): fix invalid pattern for URL validation
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/UtilsIntegrationTest.java
Labels: waiting for review

#3195 Reject member open applications during removal
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/MembersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/MembersManagerImplApi.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/RegistrarManager.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
  perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/RegistrarBaseIntegrationTest.java
Labels: waiting for changes

#3233 Bumped development version to 3.26.0-SNAPSHOT
  perun-auditlogger/pom.xml
  perun-auditparser/pom.xml
  perun-base/pom.xml
  perun-cabinet/pom.xml
  perun-cli-java/pom.xml
  perun-cli/Perun/Agent.pm
  perun-core/pom.xml
  perun-dispatcher/pom.xml
  perun-engine/pom.xml
  perun-ldapc/pom.xml
  perun-notification/pom.xml
  perun-openapi/openapi.yml
  perun-openapi/pom.xml
  perun-registrar-lib/pom.xml
  perun-rpc/pom.xml
  perun-scim/pom.xml
  perun-voot/pom.xml
  perun-web-gui/pom.xml
  pom.xml
Labels: waiting for review
