Repository CESNET/perun, pull requests merged in 2021-03, with the labels that each got.

#3108 Core - fix getRichUsersFromListOfUsers methods
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/UsersManagerEntry.java
Labels: waiting for review

#3111 Deleting unused destinations
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ServicesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ServicesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ServicesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/ServicesManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/ServicesManagerEntryIntegrationTest.java
Labels: merge soon

#3110 Core - createSponsoredMembersFromCsv, groups
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/MembersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/MembersManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/MembersManagerMethod.java
Labels: merge soon

#3114 DISPATCHER: Fix WAITING tasks re-scheduling
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/scheduling/PropagationMaintainer.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/scheduling/impl/SchedulingPoolImpl.java
Labels: merge soon

#3113 Handle sending of JMS messages in comm thread.
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/jms/EngineMessageConsumer.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/jms/EngineMessageProcessor.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/jms/EngineMessageProducer.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/jms/EngineMessageProducerFactory.java
  perun-engine/src/main/java/cz/metacentrum/perun/engine/jms/JMSQueueManager.java
  perun-engine/src/main/java/cz/metacentrum/perun/engine/jms/MessageReceiver.java
  perun-engine/src/main/java/cz/metacentrum/perun/engine/runners/GenCollector.java
  perun-engine/src/main/java/cz/metacentrum/perun/engine/runners/SendCollector.java
  perun-engine/src/main/java/cz/metacentrum/perun/engine/scheduling/impl/PropagationMaintainerImpl.java
  perun-engine/src/main/java/cz/metacentrum/perun/engine/scheduling/impl/SchedulingPoolImpl.java
Labels: merge soon

#3122 CORE: Removed local pwd strength check for MU
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/MuPasswordManagerModule.java
Labels: merge soon

#3125 Core - members pagination
  perun-base/src/main/java/cz/metacentrum/perun/core/api/MembersOrderColumn.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/MembersPageQuery.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/Paginated.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/SortingOrder.java
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/MembersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/MembersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/MembersManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/MembersManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/MembersManagerMethod.java
Labels: waiting for review

#3126 Reducing debug logs in AuditLogger
  perun-auditlogger/src/main/java/cz/metacentrum/perun/auditlogger/logger/impl/EventLoggerImpl.java
Labels: merge soon

#2197 Changes for o365 email modules
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_o365EmailAddresses_o365mu.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_resource_attribute_def_def_o365EmailAddresses_mu.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_attribute_def_def_o365EmailAddresses_mu.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_o365SystemEmailAddresses_mu.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_o365UserEmailAddresses_mu.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_def_o365EmailAddresses_o365muTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_attribute_def_def_o365EmailAddresses_muTest.java
Labels: don't merge, waiting for review

#3136 member attr o365EmailAddresses_mu fix
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_attribute_def_def_o365EmailAddresses_mu.java
Labels: waiting for review

#3138 Password reset using UUID as token
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/java/cz/metacentrum/perun/core/api/UsersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/UsersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/UsersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/UsersManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/MembersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/UsersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/MembersManagerImplApi.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/UsersManagerImplApi.java
  perun-core/src/main/resources/postgresChangelog.txt
  perun-db/postgres.sql
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/UsersManagerMethod.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/usersManager/ChangeNonAuthzPassword.java
Labels: merge soon

#3141 CORE: Fixed sponsored member creation at MU
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/MuPasswordManagerModule.java
Labels: merge soon

#3137 Suspending propagating tasks to engine
  perun-base/src/main/resources/perun-roles.yml
  perun-cli/Perun/TasksAgent.pm
  perun-cli/resumeTasksPropagation
  perun-cli/suspendTasksPropagation
  perun-core/src/main/java/cz/metacentrum/perun/core/api/TasksManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/TasksManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/TasksManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/TasksManagerEntry.java
  perun-dispatcher/src/main/java/cz/metacentrum/perun/dispatcher/scheduling/TaskScheduler.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/TasksManagerMethod.java
Labels: merge soon

#3146 Core - new methods for group stats
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/GroupsManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/GroupsManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/GroupsManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupsManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/GroupsManagerMethod.java
Labels: merge soon
