Repository CESNET/perun, pull requests merged in 2022-08, with the labels that each got.

#3662 feat(core): push new attributes to LDAP
  perun-ldapc/src/main/resources/perun-ldapc.xml
Labels: waiting for review

#3661 feat(core): extended LDAP schema with rpName for facility
  perun-utils/ldapc-scripts/schemas/perun-schema.ldif
Labels: waiting for review

#3666 fix(core): add privilege for members to get facilities and resources
  perun-base/src/main/resources/perun-roles.yml
Labels: waiting for review

#3668 feat(core): add mfaCriticalObject attributes when initializing Perun
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
Labels: waiting for review

#3654 feat(core): added consolidate method and call to userInfoEndpoint whe…
  perun-base/pom.xml
  perun-base/src/main/java/cz/metacentrum/perun/core/api/CoreConfig.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/EnrichedExtSource.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ExpiredTokenException.java
  perun-base/src/main/java/cz/metacentrum/perun/oidc/UserInfoEndpointCall.java
  perun-base/src/main/java/cz/metacentrum/perun/oidc/UserInfoEndpointResponse.java
  perun-base/src/main/java/cz/metacentrum/perun/registrar/model/EnrichedIdentity.java
  perun-base/src/main/resources/perun-base.xml
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/PerunBlImpl.java
  perun-openapi/openapi.yml
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/ConsolidatorManager.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/ConsolidatorManagerImpl.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/Api.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/RegistrarManagerMethod.java
Labels: waiting for review

#3671 feat(core): mark critical operations in FacilitiesManager
  perun-base/src/main/resources/perun-roles.yml
Labels: waiting for review

#3670 feat(core): mark critical methods in Attributes, AuditMessages and Au…
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/AttributesManagerEntry.java
Labels: waiting for review

#3674 feat(core): critical operations in GroupsManager
  perun-base/src/main/resources/perun-roles.yml
Labels: waiting for review

#3676 fix(core): fixed error handling from calls to userInfoEndpoint
  perun-base/src/main/java/cz/metacentrum/perun/oidc/UserInfoEndpointCall.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/ConsolidatorManagerImpl.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/Api.java
Labels: waiting for review

#3678 feat(core) mark critical operations in Vos Manager
  perun-base/src/main/resources/perun-roles.yml
Labels: waiting for review

#3672 feat(core) mark critical operations in Owners and Resources managers
  perun-base/src/main/resources/perun-roles.yml
Labels: waiting for review

#3677 feat(core): critical operations in UsersManager
  perun-base/src/main/resources/perun-roles.yml
Labels: waiting for review

#3684 feat: new method getMessagesByIdAndCount
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/AuditMessagesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/AuditMessagesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuditMessagesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/AuditMessagesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AuditMessagesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/AuditMessagesManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/AuditMessagesManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/AuditMessagesManagerMethod.java
Labels: waiting for review

#3683 feat: critical operations in Registrar, Mail, Notif, Consent managers
  perun-base/src/main/resources/perun-roles.yml
Labels: waiting for review

#3680 feat(core): flag critical actions on attributes
  perun-base/src/main/java/cz/metacentrum/perun/core/api/AttributeRules.java
  perun-base/src/main/resources/perun-roles.yml
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/java/cz/metacentrum/perun/core/api/AttributesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/AttributesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/AttributesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AttributesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/AttributesManagerImplApi.java
  perun-core/src/main/resources/perun-core.xml
  perun-core/src/main/resources/postgresChangelog.txt
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/AttributesManagerEntryIntegrationTest.java
  perun-db/postgres.sql
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/AttributesManagerMethod.java
  perun-utils/rpc-methods-javadoc-generator/parseRpcMethods.pl
Labels: waiting for review

#3685 feat(cli): scripts for critical attribute actions
  perun-cli/Perun/AttributesAgent.pm
  perun-cli/Perun/Common.pm
  perun-cli/Perun/beans/AttributeRules.pm
  perun-cli/getAttributePolicyCollections
  perun-cli/setAttributeCriticalActions
Labels: waiting for review

#3679 fix(core): deleting an attribute with a namespace could remove common…
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AttributesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/AttributesManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/AttributesManagerEntryIntegrationTest.java
Labels: waiting for review

#3686 feat(core): add MFA role to principal roles
  perun-base/src/main/java/cz/metacentrum/perun/core/api/CoreConfig.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/PerunPrincipal.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/Role.java
  perun-base/src/main/java/cz/metacentrum/perun/oidc/UserInfoEndpointCall.java
  perun-base/src/main/resources/perun-base.xml
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/ConsolidatorManagerImpl.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/Api.java
Labels: manually tested

#3687 fix(core): allow null domain in brand check
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunAppsConfig.java
Labels: waiting for review, manually tested

#3688 feat(core): support HTML footers in mail notifications
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/MailManagerImpl.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
Labels: waiting for review

#3689 refactor(core): removed module for attr f:d:homeMountPoint_passwd-scp
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_homeMountPoint_passwd_scp.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_facility_attribute_def_def_homeMountPoint_passwd_scpTest.java
Labels: merge soon

#3690 feat(core): refresh mfa
  perun-base/src/main/java/cz/metacentrum/perun/core/api/CoreConfig.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/PerunPrincipal.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/MFAuthenticationException.java
  perun-base/src/main/java/cz/metacentrum/perun/oidc/UserInfoEndpointCall.java
  perun-base/src/main/resources/perun-base.xml
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/AuthzResolver.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/Api.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/AuthzResolverMethod.java
Labels: waiting for review

#3694 fix(registrar): quick-fix duplicate notifications
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
Labels: waiting for review
