Repository CESNET/perun, pull requests merged in 2022-06, with the labels that each got.

#3613 refactor(core): improved javadoc and errors in u_f:d:homeMountPoint module
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_def_homeMountPoint.java
Labels: waiting for review, merge soon

#3616 fix(core): allow null memberOrganizations
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_attribute_def_def_memberOrganizations.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_attribute_def_def_memberOrganizationsTest.java
Labels: waiting for review

#3618 refactor(core): disable alt passwords in einfra
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/EinfraPasswordManagerModule.java
Labels: waiting for review, merge soon

#3622 fix(core): correctly handle empty policyCollection in setAttributePolicyCollections
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AttributesManagerImpl.java
Labels: waiting for review

#3620 feat(core): check Role + RoleObject combinations when setting attribute policies
  perun-base/src/main/java/cz/metacentrum/perun/core/api/RoleManagementRules.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/RoleObjectCombinationInvalidException.java
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/AttributesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/AttributesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunRolesLoader.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/AttributesManagerEntryIntegrationTest.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/AttributesManagerMethod.java
Labels: waiting for review

#3623 feat(core): support assigning attribute policies to SecurityAdmin role
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
Labels: waiting for review

#3624 feat: script for attribute rights migration
  perun-db/migrateAttributeRights
Labels: waiting for review

#3621 feat(registrar): enabled HTML in email notifications
  perun-base/src/main/java/cz/metacentrum/perun/registrar/model/ApplicationMail.java
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/resources/postgresChangelog.txt
  perun-db/postgres.sql
  perun-openapi/openapi.yml
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/MailManagerImpl.java
  perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/RegistrarBaseIntegrationTest.java
Labels: waiting for review

#3627 feat: changes to allow assigning roles to SecurityTeam object
  perun-base/src/main/java/cz/metacentrum/perun/core/api/RoleObject.java
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/resources/postgresChangelog.txt
  perun-db/postgres.sql
  perun-openapi/openapi.yml
Labels: waiting for changes

#3612 feat(cli): use new method of attribute rights in cli scripts
  perun-cli/Perun/AttributesAgent.pm
  perun-cli/Perun/Common.pm
  perun-cli/Perun/beans/AttributePolicy.pm
  perun-cli/Perun/beans/AttributePolicyCollection.pm
  perun-cli/Perun/beans/AttributeRights.pm
  perun-cli/getAttributePolicyCollections
  perun-cli/setAttributePolicyCollections
  perun-cli/setAttributeRights
Labels: waiting for review

#3631 feat(core): check weak passwords according to dictionary
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/EinfraPasswordManagerModule.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/GenericPasswordManagerModule.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/MuadmPasswordManagerModule.java
Labels: waiting for review

#3634 fix(core): value of member:virt:mails now contains only unique emails
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_attribute_def_virt_mails.java
Labels: waiting for review

#3609 fix(rpc): fixed (de)serialization of LocalDate/Time properties
  perun-base/src/main/java/cz/metacentrum/perun/core/api/Ban.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/Member.java
  perun-base/src/main/java/cz/metacentrum/perun/rpc/deserializer/JsonDeserializer.java
  perun-base/src/main/java/cz/metacentrum/perun/rpc/serializer/JsonSerializer.java
  perun-base/src/main/java/cz/metacentrum/perun/rpc/serializer/JsonSerializerJSONLITE.java
  perun-base/src/main/java/cz/metacentrum/perun/rpc/serializer/JsonSerializerJSONP.java
  perun-base/src/main/java/cz/metacentrum/perun/rpc/serializer/JsonSerializerJSONSIMPLE.java
  perun-base/src/main/java/cz/metacentrum/perun/rpclib/impl/JsonSerializer.java
  perun-base/src/main/java/cz/metacentrum/perun/taskslib/model/TaskResult.java
Labels: manual test needed

#3632 feat: method to retrieve rich resources assigned to facility with selected service assigned
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/FacilitiesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/FacilitiesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/FacilitiesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/FacilitiesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/FacilitiesManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/FacilitiesManagerMethod.java
Labels: waiting for review

#3633 feat: method to retrieve services assigned to resources with selected vo on selected facility
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/ServicesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ServicesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ServicesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ServicesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ServicesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/ServicesManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/ServicesManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ServicesManagerMethod.java
Labels: waiting for review

#3637 fix(core): member_group_virt_groupStatus attribute is now initialized
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupsManagerEntryIntegrationTest.java
Labels: waiting for review

#3605 feat(cli): add more getters for (Rich)Member objects
  perun-cli/Perun/beans/Member.pm
  perun-cli/Perun/beans/RichMember.pm
  perun-cli/Perun/beans/RichUser.pm
  perun-cli/Perun/beans/User.pm
Labels: merge soon

#3640 fix(gui): support HTML message property in notification objects
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/registrarManager/UpdateApplicationMail.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/model/ApplicationMail.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/model/MailText.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/registrartabs/CreateMailTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/registrartabs/EditMailTabItem.java
Labels: merge soon

#3641 feat(core): add optional login in password strength check
  perun-core/src/main/java/cz/metacentrum/perun/core/api/UsersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/UsersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/UsersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/UsersManagerEntry.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/UsersManagerMethod.java
Labels: waiting for review

#3644 fix(core): LSAAI password module validation
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/pwdmgr/LifescienceidusernamePasswordManagerModule.java
Labels: waiting for review

#3562 fix(gui): properly resize table with application detail
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/registrartabs/ApplicationDetailTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/userstabs/SelfApplicationDetailTabItem.java
Labels: merge soon

#3647 feat(openapi): added method setLogin() to openapi
  perun-openapi/openapi.yml
Labels: waiting for review
