Repository CESNET/perun, pull requests merged in 2022-11, with the labels that each got.

#3753 fix(registrar): fix duplicate notifications
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/resources/postgresChangelog.txt
  perun-db/postgres.sql
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
Labels: waiting for review

#3760 fix(core): fix createGroupUnion sql exception
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/GroupsManagerImpl.java
Labels: waiting for review

#3758 feat(core): support branding between new and old GUI
  perun-base/src/test/resources/perun-apps-config.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunAppsConfig.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/PerunAppsConfigLoaderTest.java
  perun-openapi/openapi.yml
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/MailManagerImpl.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/Api.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/client/PerunWebSession.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/client/WebGui.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/GetNewGuiAlert.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/attributestabs/AttributeDefinitionDetailTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/attributestabs/CreateAttributeDefinitionTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/entitylessattributestabs/EntitylessAttributesDetailTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/registrartabs/CreateMailTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/registrartabs/EditMailTabItem.java
Labels: waiting for review

#3762 feat(cli): refactored setRole and unsetRole scripts to work with any …
  perun-cli/Perun/AuthzResolverAgent.pm
  perun-cli/Perun/Common.pm
  perun-cli/Perun/beans/RoleManagementRules.pm
  perun-cli/setRole
  perun-cli/unsetRole
Labels: waiting for review

#3765 feat(core): add virt attribute isBanned for Facility
  perun-base/src/main/java/cz/metacentrum/perun/audit/events/AttributesManagerEvents/AttributeChangedForFacilityAndUser.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_virt_isBanned.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_virt_isBannedTest.java
Labels: waiting for review

#3769 fix(core): fixed search for publications in OBD from ZČU
  perun-cabinet/src/main/java/cz/metacentrum/perun/cabinet/strategy/impl/OBD30Strategy.java
  perun-cabinet/src/test/java/cz/metacentrum/perun/cabinet/CabinetBaseIntegrationTest.java
Labels: merge soon

#3766 fix(openapi): Fix getBansForResource param name
  perun-cli/listOfBans
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ResourcesManagerMethod.java
Labels: waiting for review

#3771 fix(registrar): unable members without expiration to submit extension…
  perun-core/src/main/java/cz/metacentrum/perun/core/api/MembersManager.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
Labels: waiting for review

#3774 feat(core): return enriched bans on resource
  perun-base/src/main/java/cz/metacentrum/perun/core/api/EnrichedBanOnResource.java
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/ResourcesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ResourcesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ResourcesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ResourcesManagerMethod.java
  perun-utils/rpc-methods-javadoc-generator/parseRpcMethods.pl
Labels: waiting for review

#3773 feat(core): make roles receiving notifications configurable
  perun-base/src/main/java/cz/metacentrum/perun/core/api/RoleManagementRules.java
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/PerunRolesLoader.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/MailManagerImpl.java
Labels: waiting for review

#3780 feat(core): Enriched bans on facility
  perun-base/src/main/java/cz/metacentrum/perun/core/api/EnrichedBanOnFacility.java
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/FacilitiesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/FacilitiesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/FacilitiesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/FacilitiesManagerMethod.java
  perun-utils/rpc-methods-javadoc-generator/parseRpcMethods.pl
Labels: waiting for review

#3782 feat(registrar): allow bulk invitations
  perun-openapi/openapi.yml
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/MailManager.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/MailManagerImpl.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/RegistrarManagerMethod.java
Labels: waiting for review

#3786 fixup! feat: extended the getPerunOidcConfig method to be able to ret…
  perun-cli/Perun/Agent.pm
  perun-cli/getOidcConfig
Labels: waiting for review

#3787 fixup! feat(core): Enriched Bans On Vo
  perun-base/src/main/java/cz/metacentrum/perun/core/api/EnrichedBanOnVo.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/VosManagerEntryIntegrationTest.java
Labels: waiting for review

#3788 fix(core): fixed authorization in getAssignedGroups(resource,member)
  perun-base/src/main/resources/perun-roles.yml
Labels: waiting for review

#3789 fix(core): correctly set default date to BanOnVo/Resource/Facility wh…
  perun-base/src/main/java/cz/metacentrum/perun/core/api/Ban.java
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/VosManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/FacilitiesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ResourcesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/VosManagerImpl.java
  perun-core/src/main/resources/postgresChangelog.txt
  perun-db/postgres.sql
Labels: waiting for review, don't merge
