Repository CESNET/perun, pull requests merged in 2022-03, with the labels that each got.

#3485 fix(registrar): getApplicationsPage now returns only one application entry even if an application has multiple form data items.
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
  perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/RegistrarBaseIntegrationTest.java
Labels: waiting for review

#3479 fix: verify membership status before retrieving admin roles
  perun-core/src/main/java/cz/metacentrum/perun/core/api/FacilitiesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/GroupsManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/ResourcesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/UsersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/VosManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/FacilitiesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/GroupsManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ResourcesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/UsersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/VosManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AuthzResolverImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/FacilitiesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/GroupsManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ResourcesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/UsersManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/VosManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/AuthzResolverImplApi.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/FacilitiesManagerImplApi.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/GroupsManagerImplApi.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/ResourcesManagerImplApi.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/UsersManagerImplApi.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/VosManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/AuthzResolverImplIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/FacilitiesManagerImplIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/GroupsManagerImplIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/ResourcesManagerImplIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/UsersManagerImplIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/VosManagerImplIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/FacilitiesManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/GroupsManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ResourcesManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/UsersManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/VosManagerMethod.java
Labels: waiting for review

#3477 feat(core): load membership role to session with authorization refresh
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/GroupsManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ResourcesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ResourcesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/GroupsManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ResourcesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/GroupsManagerImplApi.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/ResourcesManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/api/AuthzResolverIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupsManagerEntryIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/ResourcesManagerEntryIntegrationTest.java
Labels: waiting for review

#3486 feat(core): push C-SCALE attributes to LDAP
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_cscaleUserCategory.java
  perun-ldapc/src/main/resources/perun-ldapc.xml
  perun-utils/ldapc-scripts/schemas/perun-schema.ldif
Labels: waiting for review

#3488 feat: add method for retrieving RichMembers for VO without user attributes
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/MembersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/MembersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/MembersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/MembersManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/MembersManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/MembersManagerMethod.java
Labels: waiting for review

#3493 feat: implement a method for reloading perun-apps-config.yml
  perun-base/src/main/resources/perun-roles.yml
  perun-cli/Perun/Agent.pm
  perun-cli/Perun/ConfigAgent.pm
  perun-cli/reloadAppsConfig
  perun-core/src/main/java/cz/metacentrum/perun/core/api/ConfigManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/Perun.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ConfigManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/PerunBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ConfigManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/PerunBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ConfigManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ConfigManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/ConfigManagerImplApi.java
  perun-core/src/main/resources/perun-core.xml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/ApiCaller.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/PerunManager.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ConfigManagerMethod.java
Labels: waiting for review

#3491 feat(core): added memberOrganizations attribute
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_attribute_def_def_memberOrganizations.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_member_attribute_def_def_memberOrganizationsTest.java
Labels: waiting for review

#3499 fix(core): added debug logs when deleting Tasks
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/TasksManagerImpl.java
Labels: merge soon

#3498 feat(core): avoid cyclic memberships
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/VosManagerBlImpl.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/VosManagerEntryIntegrationTest.java
Labels: waiting for review

#3503 feat(openapi): added method
  perun-openapi/openapi.yml
Labels: waiting for review

#3506 feat(core): forceConsents flag
  perun-base/src/main/java/cz/metacentrum/perun/core/api/CoreConfig.java
  perun-base/src/main/resources/perun-base.xml
Labels: waiting for review

#3510 feat(openapi): added methods to OpenApi
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/VosManagerMethod.java
Labels: waiting for changes

#3512 feat(core): allow storing boolean attributes from registrar
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
Labels: merge soon

#3513 feat(core): return also group name and parent group id in getGroupMemberData()
  perun-integration/src/main/java/cz/metacentrum/perun/integration/daoImpl/IntegrationManagerDaoImpl.java
  perun-integration/src/main/java/cz/metacentrum/perun/integration/model/GroupMemberRelation.java
  perun-integration/src/test/java/cz/metacentrum/perun/integration/entry/IntegrationManagerApiTest.java
  perun-openapi/openapi.yml
Labels: waiting for review

#3519 feat(core): return also user id in IntegrationManager::getGroupMemberData()
  perun-integration/src/main/java/cz/metacentrum/perun/integration/daoImpl/IntegrationManagerDaoImpl.java
  perun-integration/src/main/java/cz/metacentrum/perun/integration/model/GroupMemberRelation.java
  perun-integration/src/test/java/cz/metacentrum/perun/integration/entry/IntegrationManagerApiTest.java
  perun-openapi/openapi.yml
Labels: waiting for review

#3518 feat: new class Consent
  perun-base/src/main/java/cz/metacentrum/perun/core/api/Consent.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/ConsentStatus.java
  perun-base/src/test/resources/test-schema.sql
  perun-core/src/main/resources/postgresChangelog.txt
  perun-db/postgres.sql
  perun-openapi/openapi.yml
  perun-utils/rpc-methods-javadoc-generator/parseRpcMethods.pl
Labels: waiting for review

#3526 fix(core): fixed ssh keys value normalization in registrar
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
Labels: merge soon

#3524 feat(core): methods to create/delete/find consentHubs
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ConsentHubAlreadyRemovedException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ConsentHubExistsException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ConsentHubNotExistsException.java
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/ConsentsManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/FacilitiesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ConsentsManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/FacilitiesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ConsentsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/FacilitiesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ConsentsManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/FacilitiesManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ConsentsManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/ConsentsManagerImplApi.java
  perun-core/src/main/resources/perun-core.xml
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/ConsentsManagerEntryIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/SecurityTeamsManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ConsentsManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/FacilitiesManagerMethod.java
Labels: waiting for review
