Repository CESNET/perun, pull requests merged in 2023-04, with the labels that each got.

#3922 fix(core): allow http and mailto protocols in html attributes
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/HTMLParser.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/HTMLParserTest.java
Labels: waiting for review

#3930 fix(ldapc): handle eppns/identities ignoring case
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/model/impl/PerunUserImpl.java
Labels: manually tested

#3931 fix(registrar): load vo/group from db
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/RegistrarManager.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
Labels: waiting for review

#3933 fix(core): temporarily disable htmlParser
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/HTMLParser.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/HTMLParserTest.java
Labels: waiting for review, manual test needed, don't merge

#3932 feat(core): ServicesManager bulk methods
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ForceServicePropagationDisabledException.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/ServiceIsNotBannedException.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/ServicesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/ServicesManagerEntry.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/ServicesManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ServicesManagerMethod.java
Labels: waiting for changes

#3895 feat: sql pooling
  perun-core/pom.xml
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/ExtSourcesManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ExtSourcesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/PerunBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceCSV.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceGoogle.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceISMU.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceIdp.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceInternal.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceKerberos.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceLdap.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourcePerun.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceREMS.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceSql.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceTCS.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceUnity.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceVOOT.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceX509.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceXML.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourcesManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/ExtSourcesManagerImplApi.java
  perun-core/src/main/resources/perun-core.xml
  perun-core/src/test/java/cz/metacentrum/perun/core/AbstractPerunIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/bl/FacilitiesManagerBlImplTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/bl/ResourcesManagerBlImplTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/bl/UsersManagerBlImplTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/ExtSourcesManagerEntryIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupAndGroupStructureSynchronizationIntegrationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/ExtSourceREMSTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/ExtSourceSqlTest.java
  pom.xml
Labels: waiting for review
