Repository CESNET/perun, pull requests merged in 2023-11, with the labels that each got.

#4135 refactor(core): move module not found log message to trace
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/AttributesManagerImpl.java
Labels: waiting for review

#4124 feat(core): bulk-up public ssh key validation
  perun-base/src/main/java/cz/metacentrum/perun/core/api/exceptions/SSHKeyNotValidException.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/UsersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/UsersManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/UsersManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/UsersManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/SSHValidator.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/Utils.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_sshPublicKey.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/UtilsIntegrationTest.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/UsersManagerMethod.java
Labels: waiting for review

#4132 fix(registrar): transaction for approving multiple applications
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
Labels: waiting for review

#4136 fix(registrar): pass registrar session when submitting embedded appli…
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
Labels: waiting for review, merge soon, manually tested

#4151 fix(core): admins-related methods
  perun-core/src/main/java/cz/metacentrum/perun/core/api/AuthzResolver.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/FacilitiesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/GroupsManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/ResourcesManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/SecurityTeamsManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/api/VosManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
  perun-core/src/test/java/cz/metacentrum/perun/core/api/AuthzResolverIntegrationTest.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/FacilitiesManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/GroupsManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/ResourcesManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/SecurityTeamsManagerMethod.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/VosManagerMethod.java
Labels: waiting for review

#4104 feat(core): synchronize group membership status
  perun-base/src/main/java/cz/metacentrum/perun/core/api/Candidate.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/CandidateSync.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/GroupsManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/ExtSourcesManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceSql.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupAndGroupStructureSynchronizationIntegrationTest.java
  perun-openapi/openapi.yml
Labels: waiting for review, don't merge, manually tested
