Repository CESNET/perun, pull requests merged in 2023-07, with the labels that each got.

#3997 fix(core): change autoRegistrationEnabled attribute value
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_virt_autoRegistrationEnabled.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_group_attribute_def_virt_autoRegistrationEnabledTest.java
Labels: waiting for review

#3992 feat: create voPersonExternalAffiliation and forwardedVoPersonExterna…
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_elixirBonaFideStatus.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_forwardedVoPersonExternalAffiliation.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_studentIdentifiers.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_voPersonExternalAffiliation.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_elixirBonaFideStatusTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_forwardedVoPersonExternalAffiliationTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_studentIdentifiersTest.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_virt_voPersonExternalAffiliationTest.java
  perun-db/addProxyRolePolicies
  perun-ldapc/src/main/java/cz/metacentrum/perun/ldapc/model/PerunAttribute.java
  perun-ldapc/src/main/resources/perun-ldapc.xml
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/ElixirBonaFideStatus.java
  perun-utils/ldapc-scripts/schemas/perun-schema.ldif
Labels: waiting for review

#4004 feat(core): added 'mail.smtp.from' to configuration file
  perun-base/src/main/java/cz/metacentrum/perun/core/api/BeansUtils.java
  perun-base/src/main/java/cz/metacentrum/perun/core/api/CoreConfig.java
  perun-base/src/main/resources/perun-base.xml
  perun-base/src/test/resources/perun-tests.properties
Labels: waiting for review, manually tested

#4005 fix(core): filter candidates bases on group related roles
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/VosManagerEntry.java
Labels: waiting for review

#4006 fix(core): filter get rich users with attributes
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/UsersManagerEntry.java
Labels: waiting for review

#4013 feat(core): last successful propagation
  perun-base/src/main/java/cz/metacentrum/perun/core/api/RichDestination.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ServicesManagerImpl.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/ServicesManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
Labels: waiting for review

#3995 refactor(core): removed unused registration modules
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/Ceitec.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/EduGain.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/Elixircz.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/Sitola.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/WeNMR.java
Labels: waiting for review, merge soon

#4008 fix(cli): fixed encoding
  perun-cli/Perun/beans/Attribute.pm
  perun-cli/setAttributeCriticalActions
Labels: waiting for review

#4019 chore: change commitlint rules
  .commitlintrc.json
  .github/workflows/check.yml
Labels: waiting for review

#4000 feat(core): skip MFA for internal components
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
Labels: merge soon

#4015 fix: remove unused variable
  perun-utils/rpc-methods-javadoc-generator/parseRpcMethods.pl
Labels: waiting for review
