Repository CESNET/perun, pull requests merged in 2023-05, with the labels that each got.

#3945 fix(core): do not set attribute policy for perun admin
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
Labels: merge soon

#3953 feat(core): default blocked login checker
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/DefaultBlockedLoginChecker.java
  perun-core/src/main/resources/perun-core.xml
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/DefaultBlockedLoginCheckerTest.java
Labels: waiting for review

#3885 fix(gui): limit search for managers to vo/group members in pithia VO
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/groupstabs/AddGroupManagerFromMembersTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/groupstabs/GroupManagersTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/vostabs/AddVoManagerFromMembersTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/vostabs/VoManagersTabItem.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/tabs/vostabs/VoOverviewTabItem.java
Labels: manually tested

#3961 fix(core): fix randomly failing test
  perun-base/src/main/java/cz/metacentrum/perun/core/api/RichGroup.java
Labels: waiting for review

#3963 feat: use introspection data saved in request headers for MFA
  perun-base/src/main/java/cz/metacentrum/perun/core/api/CoreConfig.java
  perun-base/src/main/java/cz/metacentrum/perun/oidc/UserInfoEndpointCall.java
  perun-base/src/main/resources/perun-base.xml
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AuthzResolverBlImpl.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/Api.java
Labels: waiting for review, manual test needed
