Repository CESNET/perun, pull requests merged in 2023-09, with the labels that each got.

#4048 feat: 🎸 Filter out embedded groups where user is member + new method groupsManager/getGroupsWhereUserIsActiveMember
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/GroupsManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/bl/GroupsManagerBl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/GroupsManagerEntry.java
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/GroupsManagerImpl.java
  perun-core/src/main/java/cz/metacentrum/perun/core/implApi/GroupsManagerImplApi.java
  perun-core/src/test/java/cz/metacentrum/perun/core/entry/GroupsManagerEntryIntegrationTest.java
  perun-openapi/openapi.yml
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/GroupsManagerMethod.java
Labels: merge soon

#4052 feat: use journald instead of syslog in perun-auditlogger
  perun-auditlogger/src/main/java/cz/metacentrum/perun/auditlogger/logger/impl/EventLoggerImpl.java
  perun-auditlogger/src/main/java/cz/metacentrum/perun/auditlogger/service/impl/AuditLoggerManagerImpl.java
  perun-auditlogger/src/main/resources/logback.xml
  perun-auditlogger/src/main/resources/perun-auditlogger.xml
Labels: waiting for review

#4066 fix(core): enforce mfa modul - correctly retrieve mfa categories
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_mfaEnforceSettings.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_mfaEnforceSettingsTest.java
Labels: waiting for review

#4063 feat(core): new enabledO365MailForward virtual attribute
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_virt_enabledO365MailForward.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_facility_attribute_def_virt_enabledO365MailForwardTest.java
Labels: waiting for review

#4064 feat(core): approve applications method
  perun-openapi/openapi.yml
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/RegistrarManager.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
  perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/RegistrarBaseIntegrationTest.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/RegistrarManagerMethod.java
Labels: waiting for review

#4067 feat(core): delete applications method
  perun-openapi/openapi.yml
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/RegistrarManager.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
  perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/RegistrarBaseIntegrationTest.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/RegistrarManagerMethod.java
Labels: waiting for review

#4072 feat(core): reject applications method
  perun-openapi/openapi.yml
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/RegistrarManager.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
  perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/RegistrarBaseIntegrationTest.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/RegistrarManagerMethod.java
Labels: waiting for review

#4071 feat(core): resend notifications method
  perun-openapi/openapi.yml
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/MailManager.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/MailManagerImpl.java
  perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/RegistrarBaseIntegrationTest.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/RegistrarManagerMethod.java
Labels: waiting for review

#4073 fix(core): approve applications order
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
  perun-registrar-lib/src/test/java/cz/metacentrum/perun/registrar/RegistrarBaseIntegrationTest.java
Labels: waiting for review

#4088 fix(core): properly resolve members removal from authoritative groups
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
Labels: waiting for review, merge soon

#4089 feat(core): support authoritative groups in group structure synchronization
  perun-core/src/main/java/cz/metacentrum/perun/core/api/GroupsManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/GroupsManagerBlImpl.java
Labels: waiting for review, merge soon

#4082 feat(core): allow members to read their group expiration
  perun-core/src/main/java/cz/metacentrum/perun/core/blImpl/AttributesManagerBlImpl.java
Labels: waiting for review

#4060 feat: 🎸 Allow multiple reg. modules to be configured
  perun-base/src/main/java/cz/metacentrum/perun/registrar/model/ApplicationForm.java
  perun-base/src/test/resources/test-schema.sql
  perun-cli/Perun/beans/ApplicationForm.pm
  perun-cli/updateForm
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/GroupsManagerImpl.java
  perun-core/src/main/resources/postgresChangelog.txt
  perun-db/postgres.sql
  perun-openapi/openapi.yml
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/impl/RegistrarManagerImpl.java
  perun-registrar-lib/src/main/java/cz/metacentrum/perun/registrar/modules/EscPithiaOrganizations.java
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/RegistrarManagerMethod.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/json/registrarManager/GetApplicationForm.java
  perun-web-gui/src/main/java/cz/metacentrum/perun/webgui/model/ApplicationForm.java
Labels: waiting for review

#4090 feat(core): new ExtSource type for IT4I
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/ExtSourceIT4I.java
Labels: merge soon

#4096 feat(core): add getAssociatedResources to RPC and openapi
  perun-base/src/main/resources/perun-roles.yml
  perun-core/src/main/java/cz/metacentrum/perun/core/api/UsersManager.java
  perun-core/src/main/java/cz/metacentrum/perun/core/entry/UsersManagerEntry.java
  perun-openapi/openapi.yml
  perun-rpc/src/main/java/cz/metacentrum/perun/rpc/methods/UsersManagerMethod.java
Labels: waiting for review

#4095 feat(core): mfa categories use namespace as key
  perun-core/src/main/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_mfaEnforceSettings.java
  perun-core/src/test/java/cz/metacentrum/perun/core/impl/modules/attributes/urn_perun_user_attribute_def_def_mfaEnforceSettingsTest.java
Labels: waiting for review
